# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

extend = [{ path = "./tools/scripts/data.toml"}, { path = "./tools/scripts/valgrind.toml"},
          { path = "./tools/scripts/tidy.toml"}, { path = "./tools/scripts/wasm.toml"},
          { path = "./tools/scripts/tests.toml"}]

[config]
default_to_workspace = false


[tasks.quick]
description = "Run quick version of all lints and tests"
category = "ICU4X Development"
dependencies = [
    "test-all-features",
    "tidy",
    "clippy-all",
    "test-ffi",
    "test-cppdoc",
]

[tasks.tidy]
description = "Run fmt and other tidy checks"
category = "ICU4X Development"
dependencies = [
    "fmt-check",
    "ci-job-tidy",
]

[tasks.ci-job-check]
description = "Run all tests for the CI 'check' job"
category = "ICU4X Development"
command = "cargo"
args = ["check", "--all-targets", "--all-features"]

[tasks.ci-job-test]
description = "Run all tests for the CI 'test' job"
category = "CI"
dependencies = [
    "test-all-features",
    "test-ffi",
    "test-docs-default",
    "test-docs",
    "bincode-gen-testdata",
]

[tasks.ci-job-features]
description = "Run all tests for the CI 'features' job"
category = "CI"
dependencies = [
    "build-all-features",
]

[tasks.ci-job-fmt]
description = "Run all tests for the CI 'fmt' job"
category = "CI"
dependencies = [
    "fmt-check",
]

[tasks.ci-job-tidy]
description = "Run all tests for the CI 'tidy' job"
category = "CI"
dependencies = [
    "license-header-check",
    "generated-readme-check",
]

[tasks.ci-job-wasm]
description = "Run all tests for the CI 'wasm' job"
category = "CI"
dependencies = [
    "wasm-test-release",
]

[tasks.ci-all]
# Note that updating this list will not update what is run on CI,
# it simply exists as a shortcut to run everything locally
description = "Locally run all CI jobs"
category = "ICU4X Development"
dependencies = [
    "ci-job-check",
    "ci-job-tidy",
    "ci-job-fmt",
    "ci-job-features",
    "ci-job-test",
    "ci-job-wasm",

    # CI runs this a little differently to allow for lint failures to show
    # up on PRs
    "clippy-all",

    # benchmarking and coverage jobs not included
]
