// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// See the [Rust documentation for `LanguageDisplay`](https://docs.rs/icu/2.3.1/icu/locale/names/enum.LanguageDisplay.html) for more information.
@meta.experimental
enum LanguageDisplayUnstable {
  // ignore: public_member_api_docs
  dialect,
  // ignore: public_member_api_docs
  standard;

}

// dart format on
