// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// See the [Rust documentation for `Script`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html) for more information.
enum Script {
  /// See the [Rust documentation for `Adlam`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Adlam) for more information.
  adlam,
  /// See the [Rust documentation for `Ahom`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Ahom) for more information.
  ahom,
  /// See the [Rust documentation for `AnatolianHieroglyphs`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.AnatolianHieroglyphs) for more information.
  anatolianHieroglyphs,
  /// See the [Rust documentation for `Arabic`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Arabic) for more information.
  arabic,
  /// See the [Rust documentation for `Armenian`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Armenian) for more information.
  armenian,
  /// See the [Rust documentation for `Avestan`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Avestan) for more information.
  avestan,
  /// See the [Rust documentation for `Balinese`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Balinese) for more information.
  balinese,
  /// See the [Rust documentation for `Bamum`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Bamum) for more information.
  bamum,
  /// See the [Rust documentation for `BassaVah`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.BassaVah) for more information.
  bassaVah,
  /// See the [Rust documentation for `Batak`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Batak) for more information.
  batak,
  /// See the [Rust documentation for `Bengali`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Bengali) for more information.
  bengali,
  /// See the [Rust documentation for `BeriaErfe`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.BeriaErfe) for more information.
  beriaErfe,
  /// See the [Rust documentation for `Bhaiksuki`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Bhaiksuki) for more information.
  bhaiksuki,
  /// See the [Rust documentation for `Bopomofo`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Bopomofo) for more information.
  bopomofo,
  /// See the [Rust documentation for `Brahmi`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Brahmi) for more information.
  brahmi,
  /// See the [Rust documentation for `Braille`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Braille) for more information.
  braille,
  /// See the [Rust documentation for `Buginese`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Buginese) for more information.
  buginese,
  /// See the [Rust documentation for `Buhid`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Buhid) for more information.
  buhid,
  /// See the [Rust documentation for `CanadianAboriginal`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.CanadianAboriginal) for more information.
  canadianAboriginal,
  /// See the [Rust documentation for `Carian`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Carian) for more information.
  carian,
  /// See the [Rust documentation for `CaucasianAlbanian`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.CaucasianAlbanian) for more information.
  caucasianAlbanian,
  /// See the [Rust documentation for `Chakma`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Chakma) for more information.
  chakma,
  /// See the [Rust documentation for `Cham`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Cham) for more information.
  cham,
  /// See the [Rust documentation for `Cherokee`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Cherokee) for more information.
  cherokee,
  /// See the [Rust documentation for `Chisoi`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Chisoi) for more information.
  chisoi,
  /// See the [Rust documentation for `Chorasmian`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Chorasmian) for more information.
  chorasmian,
  /// See the [Rust documentation for `Common`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Common) for more information.
  common,
  /// See the [Rust documentation for `Coptic`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Coptic) for more information.
  coptic,
  /// See the [Rust documentation for `Cuneiform`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Cuneiform) for more information.
  cuneiform,
  /// See the [Rust documentation for `Cypriot`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Cypriot) for more information.
  cypriot,
  /// See the [Rust documentation for `CyproMinoan`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.CyproMinoan) for more information.
  cyproMinoan,
  /// See the [Rust documentation for `Cyrillic`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Cyrillic) for more information.
  cyrillic,
  /// See the [Rust documentation for `Deseret`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Deseret) for more information.
  deseret,
  /// See the [Rust documentation for `Devanagari`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Devanagari) for more information.
  devanagari,
  /// See the [Rust documentation for `DivesAkuru`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.DivesAkuru) for more information.
  divesAkuru,
  /// See the [Rust documentation for `Dogra`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Dogra) for more information.
  dogra,
  /// See the [Rust documentation for `Duployan`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Duployan) for more information.
  duployan,
  /// See the [Rust documentation for `EgyptianHieroglyphs`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.EgyptianHieroglyphs) for more information.
  egyptianHieroglyphs,
  /// See the [Rust documentation for `Elbasan`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Elbasan) for more information.
  elbasan,
  /// See the [Rust documentation for `Elymaic`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Elymaic) for more information.
  elymaic,
  /// See the [Rust documentation for `Ethiopian`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Ethiopian) for more information.
  ethiopian,
  /// See the [Rust documentation for `Garay`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Garay) for more information.
  garay,
  /// See the [Rust documentation for `Georgian`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Georgian) for more information.
  georgian,
  /// See the [Rust documentation for `Glagolitic`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Glagolitic) for more information.
  glagolitic,
  /// See the [Rust documentation for `Gothic`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Gothic) for more information.
  gothic,
  /// See the [Rust documentation for `Grantha`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Grantha) for more information.
  grantha,
  /// See the [Rust documentation for `Greek`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Greek) for more information.
  greek,
  /// See the [Rust documentation for `Gujarati`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Gujarati) for more information.
  gujarati,
  /// See the [Rust documentation for `GunjalaGondi`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.GunjalaGondi) for more information.
  gunjalaGondi,
  /// See the [Rust documentation for `Gurmukhi`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Gurmukhi) for more information.
  gurmukhi,
  /// See the [Rust documentation for `GurungKhema`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.GurungKhema) for more information.
  gurungKhema,
  /// See the [Rust documentation for `Han`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Han) for more information.
  han,
  /// See the [Rust documentation for `Hangul`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Hangul) for more information.
  hangul,
  /// See the [Rust documentation for `HanifiRohingya`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.HanifiRohingya) for more information.
  hanifiRohingya,
  /// See the [Rust documentation for `Hanunoo`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Hanunoo) for more information.
  hanunoo,
  /// See the [Rust documentation for `Hatran`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Hatran) for more information.
  hatran,
  /// See the [Rust documentation for `Hebrew`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Hebrew) for more information.
  hebrew,
  /// See the [Rust documentation for `Hiragana`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Hiragana) for more information.
  hiragana,
  /// See the [Rust documentation for `ImperialAramaic`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.ImperialAramaic) for more information.
  imperialAramaic,
  /// See the [Rust documentation for `Inherited`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Inherited) for more information.
  inherited,
  /// See the [Rust documentation for `InscriptionalPahlavi`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.InscriptionalPahlavi) for more information.
  inscriptionalPahlavi,
  /// See the [Rust documentation for `InscriptionalParthian`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.InscriptionalParthian) for more information.
  inscriptionalParthian,
  /// See the [Rust documentation for `Javanese`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Javanese) for more information.
  javanese,
  /// See the [Rust documentation for `Kaithi`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Kaithi) for more information.
  kaithi,
  /// See the [Rust documentation for `Kannada`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Kannada) for more information.
  kannada,
  /// See the [Rust documentation for `Katakana`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Katakana) for more information.
  katakana,
  /// See the [Rust documentation for `Kawi`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Kawi) for more information.
  kawi,
  /// See the [Rust documentation for `KayahLi`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.KayahLi) for more information.
  kayahLi,
  /// See the [Rust documentation for `Kharoshthi`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Kharoshthi) for more information.
  kharoshthi,
  /// See the [Rust documentation for `KhitanSmallScript`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.KhitanSmallScript) for more information.
  khitanSmallScript,
  /// See the [Rust documentation for `Khmer`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Khmer) for more information.
  khmer,
  /// See the [Rust documentation for `Khojki`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Khojki) for more information.
  khojki,
  /// See the [Rust documentation for `Khudawadi`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Khudawadi) for more information.
  khudawadi,
  /// See the [Rust documentation for `KiratRai`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.KiratRai) for more information.
  kiratRai,
  /// See the [Rust documentation for `Lao`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Lao) for more information.
  lao,
  /// See the [Rust documentation for `Latin`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Latin) for more information.
  latin,
  /// See the [Rust documentation for `Lepcha`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Lepcha) for more information.
  lepcha,
  /// See the [Rust documentation for `Limbu`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Limbu) for more information.
  limbu,
  /// See the [Rust documentation for `LinearA`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.LinearA) for more information.
  linearA,
  /// See the [Rust documentation for `LinearB`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.LinearB) for more information.
  linearB,
  /// See the [Rust documentation for `Lisu`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Lisu) for more information.
  lisu,
  /// See the [Rust documentation for `Lycian`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Lycian) for more information.
  lycian,
  /// See the [Rust documentation for `Lydian`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Lydian) for more information.
  lydian,
  /// See the [Rust documentation for `Mahajani`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Mahajani) for more information.
  mahajani,
  /// See the [Rust documentation for `Makasar`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Makasar) for more information.
  makasar,
  /// See the [Rust documentation for `Malayalam`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Malayalam) for more information.
  malayalam,
  /// See the [Rust documentation for `Mandaic`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Mandaic) for more information.
  mandaic,
  /// See the [Rust documentation for `Manichaean`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Manichaean) for more information.
  manichaean,
  /// See the [Rust documentation for `Marchen`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Marchen) for more information.
  marchen,
  /// See the [Rust documentation for `MasaramGondi`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.MasaramGondi) for more information.
  masaramGondi,
  /// See the [Rust documentation for `Medefaidrin`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Medefaidrin) for more information.
  medefaidrin,
  /// See the [Rust documentation for `MeeteiMayek`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.MeeteiMayek) for more information.
  meeteiMayek,
  /// See the [Rust documentation for `MendeKikakui`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.MendeKikakui) for more information.
  mendeKikakui,
  /// See the [Rust documentation for `MeroiticCursive`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.MeroiticCursive) for more information.
  meroiticCursive,
  /// See the [Rust documentation for `MeroiticHieroglyphs`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.MeroiticHieroglyphs) for more information.
  meroiticHieroglyphs,
  /// See the [Rust documentation for `Miao`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Miao) for more information.
  miao,
  /// See the [Rust documentation for `Modi`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Modi) for more information.
  modi,
  /// See the [Rust documentation for `Mongolian`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Mongolian) for more information.
  mongolian,
  /// See the [Rust documentation for `Mro`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Mro) for more information.
  mro,
  /// See the [Rust documentation for `Multani`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Multani) for more information.
  multani,
  /// See the [Rust documentation for `Myanmar`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Myanmar) for more information.
  myanmar,
  /// See the [Rust documentation for `Nabataean`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Nabataean) for more information.
  nabataean,
  /// See the [Rust documentation for `NagMundari`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.NagMundari) for more information.
  nagMundari,
  /// See the [Rust documentation for `Nandinagari`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Nandinagari) for more information.
  nandinagari,
  /// See the [Rust documentation for `Nastaliq`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Nastaliq) for more information.
  nastaliq,
  /// See the [Rust documentation for `NewTaiLue`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.NewTaiLue) for more information.
  newTaiLue,
  /// See the [Rust documentation for `Newa`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Newa) for more information.
  newa,
  /// See the [Rust documentation for `Nko`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Nko) for more information.
  nko,
  /// See the [Rust documentation for `Nushu`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Nushu) for more information.
  nushu,
  /// See the [Rust documentation for `NyiakengPuachueHmong`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.NyiakengPuachueHmong) for more information.
  nyiakengPuachueHmong,
  /// See the [Rust documentation for `Ogham`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Ogham) for more information.
  ogham,
  /// See the [Rust documentation for `OlChiki`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.OlChiki) for more information.
  olChiki,
  /// See the [Rust documentation for `OlOnal`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.OlOnal) for more information.
  olOnal,
  /// See the [Rust documentation for `OldHungarian`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.OldHungarian) for more information.
  oldHungarian,
  /// See the [Rust documentation for `OldItalic`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.OldItalic) for more information.
  oldItalic,
  /// See the [Rust documentation for `OldNorthArabian`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.OldNorthArabian) for more information.
  oldNorthArabian,
  /// See the [Rust documentation for `OldPermic`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.OldPermic) for more information.
  oldPermic,
  /// See the [Rust documentation for `OldPersian`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.OldPersian) for more information.
  oldPersian,
  /// See the [Rust documentation for `OldSogdian`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.OldSogdian) for more information.
  oldSogdian,
  /// See the [Rust documentation for `OldSouthArabian`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.OldSouthArabian) for more information.
  oldSouthArabian,
  /// See the [Rust documentation for `OldTurkic`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.OldTurkic) for more information.
  oldTurkic,
  /// See the [Rust documentation for `OldUyghur`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.OldUyghur) for more information.
  oldUyghur,
  /// See the [Rust documentation for `Oriya`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Oriya) for more information.
  oriya,
  /// See the [Rust documentation for `Osage`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Osage) for more information.
  osage,
  /// See the [Rust documentation for `Osmanya`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Osmanya) for more information.
  osmanya,
  /// See the [Rust documentation for `PahawhHmong`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.PahawhHmong) for more information.
  pahawhHmong,
  /// See the [Rust documentation for `Palmyrene`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Palmyrene) for more information.
  palmyrene,
  /// See the [Rust documentation for `PauCinHau`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.PauCinHau) for more information.
  pauCinHau,
  /// See the [Rust documentation for `PhagsPa`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.PhagsPa) for more information.
  phagsPa,
  /// See the [Rust documentation for `Phoenician`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Phoenician) for more information.
  phoenician,
  /// See the [Rust documentation for `PsalterPahlavi`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.PsalterPahlavi) for more information.
  psalterPahlavi,
  /// See the [Rust documentation for `Rejang`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Rejang) for more information.
  rejang,
  /// See the [Rust documentation for `Runic`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Runic) for more information.
  runic,
  /// See the [Rust documentation for `Samaritan`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Samaritan) for more information.
  samaritan,
  /// See the [Rust documentation for `Saurashtra`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Saurashtra) for more information.
  saurashtra,
  /// See the [Rust documentation for `Sharada`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Sharada) for more information.
  sharada,
  /// See the [Rust documentation for `Shavian`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Shavian) for more information.
  shavian,
  /// See the [Rust documentation for `Siddham`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Siddham) for more information.
  siddham,
  /// See the [Rust documentation for `Sidetic`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Sidetic) for more information.
  sidetic,
  /// See the [Rust documentation for `SignWriting`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.SignWriting) for more information.
  signWriting,
  /// See the [Rust documentation for `Sinhala`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Sinhala) for more information.
  sinhala,
  /// See the [Rust documentation for `Sogdian`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Sogdian) for more information.
  sogdian,
  /// See the [Rust documentation for `SoraSompeng`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.SoraSompeng) for more information.
  soraSompeng,
  /// See the [Rust documentation for `Soyombo`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Soyombo) for more information.
  soyombo,
  /// See the [Rust documentation for `Sundanese`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Sundanese) for more information.
  sundanese,
  /// See the [Rust documentation for `Sunuwar`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Sunuwar) for more information.
  sunuwar,
  /// See the [Rust documentation for `SylotiNagri`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.SylotiNagri) for more information.
  sylotiNagri,
  /// See the [Rust documentation for `Syriac`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Syriac) for more information.
  syriac,
  /// See the [Rust documentation for `Tagalog`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Tagalog) for more information.
  tagalog,
  /// See the [Rust documentation for `Tagbanwa`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Tagbanwa) for more information.
  tagbanwa,
  /// See the [Rust documentation for `TaiLe`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.TaiLe) for more information.
  taiLe,
  /// See the [Rust documentation for `TaiTham`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.TaiTham) for more information.
  taiTham,
  /// See the [Rust documentation for `TaiViet`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.TaiViet) for more information.
  taiViet,
  /// See the [Rust documentation for `TaiYo`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.TaiYo) for more information.
  taiYo,
  /// See the [Rust documentation for `Takri`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Takri) for more information.
  takri,
  /// See the [Rust documentation for `Tamil`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Tamil) for more information.
  tamil,
  /// See the [Rust documentation for `Tangsa`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Tangsa) for more information.
  tangsa,
  /// See the [Rust documentation for `Tangut`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Tangut) for more information.
  tangut,
  /// See the [Rust documentation for `Telugu`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Telugu) for more information.
  telugu,
  /// See the [Rust documentation for `Thaana`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Thaana) for more information.
  thaana,
  /// See the [Rust documentation for `Thai`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Thai) for more information.
  thai,
  /// See the [Rust documentation for `Tibetan`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Tibetan) for more information.
  tibetan,
  /// See the [Rust documentation for `Tifinagh`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Tifinagh) for more information.
  tifinagh,
  /// See the [Rust documentation for `Tirhuta`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Tirhuta) for more information.
  tirhuta,
  /// See the [Rust documentation for `Todhri`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Todhri) for more information.
  todhri,
  /// See the [Rust documentation for `TolongSiki`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.TolongSiki) for more information.
  tolongSiki,
  /// See the [Rust documentation for `Toto`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Toto) for more information.
  toto,
  /// See the [Rust documentation for `TuluTigalari`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.TuluTigalari) for more information.
  tuluTigalari,
  /// See the [Rust documentation for `Ugaritic`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Ugaritic) for more information.
  ugaritic,
  /// See the [Rust documentation for `Unknown`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Unknown) for more information.
  unknown,
  /// See the [Rust documentation for `Vai`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Vai) for more information.
  vai,
  /// See the [Rust documentation for `Vithkuqi`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Vithkuqi) for more information.
  vithkuqi,
  /// See the [Rust documentation for `Wancho`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Wancho) for more information.
  wancho,
  /// See the [Rust documentation for `WarangCiti`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.WarangCiti) for more information.
  warangCiti,
  /// See the [Rust documentation for `Yezidi`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Yezidi) for more information.
  yezidi,
  /// See the [Rust documentation for `Yi`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.Yi) for more information.
  yi,
  /// See the [Rust documentation for `ZanabazarSquare`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#associatedconstant.ZanabazarSquare) for more information.
  zanabazarSquare;

  int get _ffi {
    switch (this) {
      case adlam:
        return 167;
      case ahom:
        return 161;
      case anatolianHieroglyphs:
        return 156;
      case arabic:
        return 2;
      case armenian:
        return 3;
      case avestan:
        return 117;
      case balinese:
        return 62;
      case bamum:
        return 130;
      case bassaVah:
        return 134;
      case batak:
        return 63;
      case bengali:
        return 4;
      case beriaErfe:
        return 208;
      case bhaiksuki:
        return 168;
      case bopomofo:
        return 5;
      case brahmi:
        return 65;
      case braille:
        return 46;
      case buginese:
        return 55;
      case buhid:
        return 44;
      case canadianAboriginal:
        return 40;
      case carian:
        return 104;
      case caucasianAlbanian:
        return 159;
      case chakma:
        return 118;
      case cham:
        return 66;
      case cherokee:
        return 6;
      case chisoi:
        return 254;
      case chorasmian:
        return 189;
      case common:
        return 0;
      case coptic:
        return 7;
      case cuneiform:
        return 101;
      case cypriot:
        return 47;
      case cyproMinoan:
        return 193;
      case cyrillic:
        return 8;
      case deseret:
        return 9;
      case devanagari:
        return 10;
      case divesAkuru:
        return 190;
      case dogra:
        return 178;
      case duployan:
        return 135;
      case egyptianHieroglyphs:
        return 71;
      case elbasan:
        return 136;
      case elymaic:
        return 185;
      case ethiopian:
        return 11;
      case garay:
        return 201;
      case georgian:
        return 12;
      case glagolitic:
        return 56;
      case gothic:
        return 13;
      case grantha:
        return 137;
      case greek:
        return 14;
      case gujarati:
        return 15;
      case gunjalaGondi:
        return 179;
      case gurmukhi:
        return 16;
      case gurungKhema:
        return 202;
      case han:
        return 17;
      case hangul:
        return 18;
      case hanifiRohingya:
        return 182;
      case hanunoo:
        return 43;
      case hatran:
        return 162;
      case hebrew:
        return 19;
      case hiragana:
        return 20;
      case imperialAramaic:
        return 116;
      case inherited:
        return 1;
      case inscriptionalPahlavi:
        return 122;
      case inscriptionalParthian:
        return 125;
      case javanese:
        return 78;
      case kaithi:
        return 120;
      case kannada:
        return 21;
      case katakana:
        return 22;
      case kawi:
        return 198;
      case kayahLi:
        return 79;
      case kharoshthi:
        return 57;
      case khitanSmallScript:
        return 191;
      case khmer:
        return 23;
      case khojki:
        return 157;
      case khudawadi:
        return 145;
      case kiratRai:
        return 203;
      case lao:
        return 24;
      case latin:
        return 25;
      case lepcha:
        return 82;
      case limbu:
        return 48;
      case linearA:
        return 83;
      case linearB:
        return 49;
      case lisu:
        return 131;
      case lycian:
        return 107;
      case lydian:
        return 108;
      case mahajani:
        return 160;
      case makasar:
        return 180;
      case malayalam:
        return 26;
      case mandaic:
        return 84;
      case manichaean:
        return 121;
      case marchen:
        return 169;
      case masaramGondi:
        return 175;
      case medefaidrin:
        return 181;
      case meeteiMayek:
        return 115;
      case mendeKikakui:
        return 140;
      case meroiticCursive:
        return 141;
      case meroiticHieroglyphs:
        return 86;
      case miao:
        return 92;
      case modi:
        return 163;
      case mongolian:
        return 27;
      case mro:
        return 149;
      case multani:
        return 164;
      case myanmar:
        return 28;
      case nabataean:
        return 143;
      case nagMundari:
        return 199;
      case nandinagari:
        return 187;
      case nastaliq:
        return 200;
      case newTaiLue:
        return 59;
      case newa:
        return 170;
      case nko:
        return 87;
      case nushu:
        return 150;
      case nyiakengPuachueHmong:
        return 186;
      case ogham:
        return 29;
      case olChiki:
        return 109;
      case olOnal:
        return 204;
      case oldHungarian:
        return 76;
      case oldItalic:
        return 30;
      case oldNorthArabian:
        return 142;
      case oldPermic:
        return 89;
      case oldPersian:
        return 61;
      case oldSogdian:
        return 184;
      case oldSouthArabian:
        return 133;
      case oldTurkic:
        return 88;
      case oldUyghur:
        return 194;
      case oriya:
        return 31;
      case osage:
        return 171;
      case osmanya:
        return 50;
      case pahawhHmong:
        return 75;
      case palmyrene:
        return 144;
      case pauCinHau:
        return 165;
      case phagsPa:
        return 90;
      case phoenician:
        return 91;
      case psalterPahlavi:
        return 123;
      case rejang:
        return 110;
      case runic:
        return 32;
      case samaritan:
        return 126;
      case saurashtra:
        return 111;
      case sharada:
        return 151;
      case shavian:
        return 51;
      case siddham:
        return 166;
      case sidetic:
        return 209;
      case signWriting:
        return 112;
      case sinhala:
        return 33;
      case sogdian:
        return 183;
      case soraSompeng:
        return 152;
      case soyombo:
        return 176;
      case sundanese:
        return 113;
      case sunuwar:
        return 205;
      case sylotiNagri:
        return 58;
      case syriac:
        return 34;
      case tagalog:
        return 42;
      case tagbanwa:
        return 45;
      case taiLe:
        return 52;
      case taiTham:
        return 106;
      case taiViet:
        return 127;
      case taiYo:
        return 210;
      case takri:
        return 153;
      case tamil:
        return 35;
      case tangsa:
        return 195;
      case tangut:
        return 154;
      case telugu:
        return 36;
      case thaana:
        return 37;
      case thai:
        return 38;
      case tibetan:
        return 39;
      case tifinagh:
        return 60;
      case tirhuta:
        return 158;
      case todhri:
        return 206;
      case tolongSiki:
        return 211;
      case toto:
        return 196;
      case tuluTigalari:
        return 207;
      case ugaritic:
        return 53;
      case unknown:
        return 103;
      case vai:
        return 99;
      case vithkuqi:
        return 197;
      case wancho:
        return 188;
      case warangCiti:
        return 146;
      case yezidi:
        return 192;
      case yi:
        return 41;
      case zanabazarSquare:
        return 177;
    }
  }

  /// See the [Rust documentation for `for_char`](https://docs.rs/icu/2.1.1/icu/properties/props/trait.EnumeratedProperty.html#tymethod.for_char) for more information.
  static Script forChar(Rune ch) {
    final result = _icu4x_Script_for_char_mv1(ch);
    return Script.values.firstWhere((v) => v._ffi == result);
  }

  /// Get the "long" name of this property value (returns empty if property value is unknown)
  ///
  /// See the [Rust documentation for `get`](https://docs.rs/icu/2.1.1/icu/properties/struct.PropertyNamesLongBorrowed.html#method.get) for more information.
  String? longName() {
    final result = _icu4x_Script_long_name_mv1(_ffi);
    if (!result.isOk) {
      return null;
    }
    return result.union.ok._toDart([], isStatic: true);
  }

  /// Get the "short" name of this property value (returns empty if property value is unknown)
  ///
  /// See the [Rust documentation for `get`](https://docs.rs/icu/2.1.1/icu/properties/struct.PropertyNamesShortBorrowed.html#method.get) for more information.
  String? shortName() {
    final result = _icu4x_Script_short_name_mv1(_ffi);
    if (!result.isOk) {
      return null;
    }
    return result.union.ok._toDart([], isStatic: true);
  }

  /// Convert to an integer value usable with ICU4C and `CodePointMapData`
  ///
  /// See the [Rust documentation for `to_icu4c_value`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#method.to_icu4c_value) for more information.
  int toIntegerValue() {
    final result = _icu4x_Script_to_integer_value_mv1(_ffi);
    return result;
  }

  /// Convert from an integer value from ICU4C or `CodePointMapData`
  ///
  /// See the [Rust documentation for `from_icu4c_value`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.Script.html#method.from_icu4c_value) for more information.
  static Script? fromIntegerValue(int other) {
    final result = _icu4x_Script_from_integer_value_mv1(other);
    if (!result.isOk) {
      return null;
    }
    return Script.values.firstWhere((v) => v._ffi == result.union.ok);
  }

  static Script? tryFromStr(String s) {
    final temp = _FinalizedArena();
    final result = _icu4x_Script_try_from_str_mv1(s._utf8AllocIn(temp.arena));
    if (!result.isOk) {
      return null;
    }
    return Script.values.firstWhere((v) => v._ffi == result.union.ok);
  }

}

@_DiplomatFfiUse('icu4x_Script_for_char_mv1')
@ffi.Native<ffi.Int32 Function(ffi.Uint32)>(isLeaf: true, symbol: 'icu4x_Script_for_char_mv1')
// ignore: non_constant_identifier_names
external int _icu4x_Script_for_char_mv1(Rune ch);

@_DiplomatFfiUse('icu4x_Script_long_name_mv1')
@ffi.Native<_ResultSliceUtf8Void Function(ffi.Int32)>(isLeaf: true, symbol: 'icu4x_Script_long_name_mv1')
// ignore: non_constant_identifier_names
external _ResultSliceUtf8Void _icu4x_Script_long_name_mv1(int self);

@_DiplomatFfiUse('icu4x_Script_short_name_mv1')
@ffi.Native<_ResultSliceUtf8Void Function(ffi.Int32)>(isLeaf: true, symbol: 'icu4x_Script_short_name_mv1')
// ignore: non_constant_identifier_names
external _ResultSliceUtf8Void _icu4x_Script_short_name_mv1(int self);

@_DiplomatFfiUse('icu4x_Script_to_integer_value_mv1')
@ffi.Native<ffi.Uint16 Function(ffi.Int32)>(isLeaf: true, symbol: 'icu4x_Script_to_integer_value_mv1')
// ignore: non_constant_identifier_names
external int _icu4x_Script_to_integer_value_mv1(int self);

@_DiplomatFfiUse('icu4x_Script_from_integer_value_mv1')
@ffi.Native<_ResultInt32Void Function(ffi.Uint16)>(isLeaf: true, symbol: 'icu4x_Script_from_integer_value_mv1')
// ignore: non_constant_identifier_names
external _ResultInt32Void _icu4x_Script_from_integer_value_mv1(int other);

@_DiplomatFfiUse('icu4x_Script_try_from_str_mv1')
@ffi.Native<_ResultInt32Void Function(_SliceUtf8)>(isLeaf: true, symbol: 'icu4x_Script_try_from_str_mv1')
// ignore: non_constant_identifier_names
external _ResultInt32Void _icu4x_Script_try_from_str_mv1(_SliceUtf8 s);

// dart format on
