// This file is part of ICU4X. For terms of use, please see the file
// called LICENSE at the top level of the ICU4X source tree
// (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

use diplomat_core::*;
use rustdoc_types::{
    Crate, GenericArg, GenericArgs, Id, Item, ItemEnum, StructKind, Type, VariantKind, Visibility,
};
use std::collections::{BTreeSet, HashSet};
use std::fmt;
use std::fs::{self, File};
use std::path::PathBuf;
mod allowlist;
use allowlist::{IGNORED_ASSOCIATED_ITEMS, IGNORED_PATHS, IGNORED_SUBSTRINGS, IGNORED_TRAITS};

static FILE_HEADER: &str = r##"# This file contains all APIs that are exposed in Rust but not over FFI, and not allowlisted in IGNORED_PATHS in tools/ffi_coverage/allowlist.rs.
# It is generated by `cargo make diplomat-coverage`.
#
# If adding an API that expands this file, please consider:
#
#  - Whether you can expose that API over FFI in the same PR (and if you do so, be sure to add a `rust_link` annotation)
#  - Whether the API already has its functionality exposed over FFI (if so, add a potentially-`hidden` `rust_link` annotation to the corresponding FFI API)
#  - Whether that API is rust-specific functionality that need not be exposed (if so, add it to the allowlist with a note, or add a `hidden` `rust_link` annotation to a related API if possible)
#  - Whether that API should be punted for later in FFI (if so, please check in with @Manishearth, @robertbastian, or @sffc)
#  - Whether the API is unstable (if so, add it to the allowlist as unstable)
#
# It is acceptable to temporarily have APIs in this file that you plan to add in a soon-upcoming PR.
#
# Please check in with @Manishearth, @robertbastian, or @sffc if you have questions

"##;
/// RustLink but without display information
#[derive(PartialEq, Eq, Debug, Clone, PartialOrd, Ord, Hash)]
struct RustLinkInfo {
    path: ast::Path,
    typ: ast::DocType,
}

impl fmt::Display for RustLinkInfo {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}#{:?}", self.path, self.typ)
    }
}

fn main() {
    run_util_api_enforcement();

    let out_path = std::env::args().nth(1);
    let doc_types = ["icu", "fixed_decimal", "icu_provider_adapters"]
        .into_iter()
        .flat_map(collect_public_types)
        .map(|(path_vec, typ)| {
            let mut path = ast::Path::empty();
            path.elements = path_vec.into_iter().map(ast::Ident::from).collect();
            RustLinkInfo { path, typ }
        })
        .filter(|rl| {
            ![
                ast::DocType::EnumVariant,
                ast::DocType::Mod,
                ast::DocType::Trait,
            ]
            .contains(&rl.typ)
        })
        .collect::<BTreeSet<_>>();

    let capi_crate = PathBuf::from(concat!(
        std::env!("CARGO_MANIFEST_DIR"),
        "/../../../ffi/capi/src/lib.rs"
    ));
    eprintln!("Loading icu_capi crate from {capi_crate:?}");
    let capi_types = ast::File::from(&syn_inline_mod::parse_and_inline_modules(&capi_crate))
        .all_rust_links()
        .into_iter()
        .cloned()
        .map(|rl| RustLinkInfo {
            path: rl.path,
            typ: rl.typ,
        })
        .collect::<BTreeSet<_>>();

    let mut file_anchor = None;
    let mut stdout_anchor = None;
    let out_stream = if let Some(out_path) = out_path {
        let stream = file_anchor.insert(File::create(out_path).expect("opening output file"));
        stream as &mut dyn std::io::Write
    } else {
        let stream = stdout_anchor.insert(std::io::stdout());
        stream as &mut dyn std::io::Write
    };
    writeln!(out_stream, "{FILE_HEADER}").unwrap();
    doc_types
        .difference(&capi_types)
        .for_each(|item| writeln!(out_stream, "{item}").unwrap());
}

fn parse_doc(krate: &str) -> &'static Crate {
    lazy_static::lazy_static! {
        static ref CRATES: elsa::sync::FrozenMap<String, Box<Crate>> = elsa::sync::FrozenMap::new();
    }

    if CRATES.get(krate).is_none() {
        eprintln!("Parsing crate {krate}");
        std::process::Command::new("rustup")
            .args(["install", "nightly-2025-09-27"])
            .output()
            .expect("failed to install nightly");
        let output = std::process::Command::new("rustup")
            .args([
                "run",
                "nightly-2025-09-27",
                "cargo",
                "rustdoc",
                "-p",
                krate,
                "--all-features",
                "--",
                "-Zunstable-options",
                "--output-format",
                "json",
            ])
            .env_remove("RUSTDOCFLAGS")
            .output()
            .expect("failed to execute rustdoc");
        if !output.status.success() {
            panic!("Rustdoc build failed with {output:?}");
        }
        let path = PathBuf::from(std::env!("CARGO_MANIFEST_DIR"))
            .join("../../../target/doc")
            .join(krate)
            .with_extension("json");
        eprintln!("Attempting to load {path:?}");
        CRATES.insert(
            krate.to_owned(),
            serde_json::from_slice(&fs::read(&path).unwrap()).unwrap(),
        );
    }
    CRATES.get(krate).unwrap()
}

fn collect_public_types(krate: &str) -> impl Iterator<Item = (Vec<String>, ast::DocType)> {
    #[derive(Debug)]
    enum In<'a> {
        Trait,
        // The Option<String> is for the trait name of an impl
        Enum(Option<&'a str>),
        Struct(Option<&'a str>),
        Type(Option<&'a str>),
    }

    fn recurse(
        item: &Item,
        krate: &Crate,
        types: &mut HashSet<(Vec<String>, ast::DocType)>,
        mut path: Vec<String>,
        path_already_extended: bool,
        inside: Option<In>,
    ) {
        fn ignored(path: &Vec<String>) -> bool {
            IGNORED_PATHS.contains(path)
                || path
                    .last()
                    .map(|l| IGNORED_SUBSTRINGS.iter().any(|i| l.contains(i)))
                    .unwrap_or(false)
        }
        /// Helper function that ensures that ignored()
        /// is respected for every type inserted
        ///
        /// (We have a check at the beginning of recurse() but that won't catch leaf nodes)
        fn insert_ty(
            types: &mut HashSet<(Vec<String>, ast::DocType)>,
            path: Vec<String>,
            ty: ast::DocType,
        ) {
            if !ignored(&path) {
                types.insert((path, ty));
            }
        }

        fn check_ignored_assoc_item(name: &str, trait_path: Option<&str>) -> bool {
            if let Some(tr) = trait_path
                && let Some(ignored) = IGNORED_ASSOCIATED_ITEMS.get(tr)
                && ignored.contains(&name)
            {
                return true;
            }
            false
        }

        if ignored(&path) || item.deprecation.is_some() {
            return;
        }
        match &item.inner {
            ItemEnum::Use(import) => {
                if !import.is_glob {
                    path.push(import.name.clone());
                }

                if let Some(item) = &krate.index.get(import.id.as_ref().unwrap()) {
                    recurse(item, krate, types, path, true, None);
                } else if let Some(item) = &krate.paths.get(import.id.as_ref().unwrap()) {
                    // This is a reexport of hidden items, which work fine in HTML doc but
                    // don't seem to be reachable anywhere in JSON.
                    if let Some(item) = import
                        .source
                        .as_str()
                        .strip_prefix("icu_provider::fallback::")
                    {
                        insert_ty(
                            types,
                            vec![
                                "icu".to_string(),
                                "locale".to_string(),
                                "fallback".to_string(),
                                item.to_string(),
                            ],
                            match item {
                                "LocaleFallbackPriority" | "LocaleFallbackSupplement" => {
                                    ast::DocType::Enum
                                }
                                "LocaleFallbackConfig" => ast::DocType::Struct,
                                e => unreachable!("{e:?}"),
                            },
                        );
                        return;
                    }

                    // External crate. This is quite complicated and while it works, I'm not sure
                    // it's correct. This basically handles the case `pub use other_crate::module::Struct`,
                    // which means we have to parse `other_crate`, then look for `module`, then look
                    // for `Struct`. Now, `module` could actually be a reexport, which is why we have to
                    // check the `Import` case when traversing the path.
                    let external_crate = parse_doc(&krate.external_crates[&item.crate_id].name);
                    let mut item = &external_crate.index[&external_crate.root];
                    for segment in import.source.split("::").skip(1) {
                        match &item.inner {
                            ItemEnum::Module(inner) => {
                                item = inner
                                    .items
                                    .iter()
                                    .map(|id| &external_crate.index[id])
                                    .find(|item| match &item.inner {
                                        ItemEnum::Use(import) => {
                                            if import.name.as_str() == segment {
                                                path.pop();
                                                true
                                            } else {
                                                false
                                            }
                                        }
                                        _ => item.name.as_deref() == Some(segment),
                                    })
                                    .expect(&import.source);
                            }
                            _ => unreachable!(),
                        }
                    }
                    recurse(item, external_crate, types, path, true, None);
                } else {
                    eprintln!("{path:?} should be in either index or paths");
                }
            }
            _ => {
                let item_name = item.name.as_ref().unwrap();
                if !path_already_extended {
                    path.push(item_name.clone());
                }
                match &item.inner {
                    ItemEnum::Module(module) => {
                        for id in &module.items {
                            recurse(&krate.index[id], krate, types, path.clone(), false, None);
                        }
                        insert_ty(types, path, ast::DocType::Mod);
                    }
                    ItemEnum::Struct(structt) => {
                        for id in &structt.impls {
                            if let ItemEnum::Impl(inner) = &krate.index[id].inner {
                                let mut trait_name = None;
                                if let Some(path) = &inner.trait_ {
                                    if IGNORED_TRAITS.contains(path.path.as_str()) {
                                        continue;
                                    }
                                    trait_name = Some(path.path.as_str());
                                }
                                for id in &inner.items {
                                    recurse(
                                        &krate.index[id],
                                        krate,
                                        types,
                                        path.clone(),
                                        false,
                                        Some(In::Struct(trait_name)),
                                    );
                                }
                            }
                        }

                        insert_ty(types, path, ast::DocType::Struct);
                    }
                    ItemEnum::Enum(enumm) => {
                        for id in &enumm.variants {
                            recurse(&krate.index[id], krate, types, path.clone(), false, None);
                        }

                        for id in &enumm.impls {
                            if let ItemEnum::Impl(inner) = &krate.index[id].inner {
                                let mut trait_name = None;
                                if let Some(path) = &inner.trait_ {
                                    if IGNORED_TRAITS.contains(path.path.as_str()) {
                                        continue;
                                    }
                                    trait_name = Some(path.path.as_str());
                                }
                                for id in &inner.items {
                                    recurse(
                                        &krate.index[id],
                                        krate,
                                        types,
                                        path.clone(),
                                        false,
                                        Some(In::Enum(trait_name)),
                                    );
                                }
                            }
                        }

                        insert_ty(types, path, ast::DocType::Enum);
                    }
                    ItemEnum::Trait(inner) => {
                        for id in &inner.items {
                            recurse(
                                &krate.index[id],
                                krate,
                                types,
                                path.clone(),
                                false,
                                Some(In::Trait),
                            );
                        }
                        insert_ty(types, path, ast::DocType::Trait);
                    }
                    ItemEnum::Constant { .. } => {
                        insert_ty(types, path, ast::DocType::Constant);
                    }
                    ItemEnum::Function(_) => {
                        let doc_type = match inside {
                            Some(In::Enum(tr)) | Some(In::Struct(tr)) | Some(In::Type(tr))
                                if check_ignored_assoc_item(item_name, tr) =>
                            {
                                return;
                            }
                            Some(In::Enum(_)) => ast::DocType::FnInEnum,
                            Some(In::Trait) => ast::DocType::FnInTrait,
                            Some(In::Struct(_)) => ast::DocType::FnInStruct,
                            Some(In::Type(_)) => ast::DocType::FnInTypedef,
                            _ => ast::DocType::Fn,
                        };
                        insert_ty(types, path, doc_type);
                    }
                    ItemEnum::Macro(_) => {
                        insert_ty(types, path, ast::DocType::Macro);
                    }
                    ItemEnum::TypeAlias(t) => {
                        if let Type::ResolvedPath(p) = &t.type_
                            && let ItemEnum::Struct(rustdoc_types::Struct { impls, .. })
                            | ItemEnum::Enum(rustdoc_types::Enum { impls, .. }) =
                                &krate.index[&p.id].inner
                        {
                            for id in impls {
                                if let ItemEnum::Impl(inner) = &krate.index[id].inner {
                                    let mut trait_name = None;
                                    if let Some(path) = &inner.trait_ {
                                        if IGNORED_TRAITS.contains(path.path.as_str()) {
                                            continue;
                                        }
                                        trait_name = Some(path.path.as_str());
                                    }
                                    for id in &inner.items {
                                        recurse(
                                            &krate.index[id],
                                            krate,
                                            types,
                                            path.clone(),
                                            false,
                                            Some(In::Type(trait_name)),
                                        );
                                    }
                                }
                            }
                        }
                        insert_ty(types, path, ast::DocType::Typedef);
                    }
                    ItemEnum::Variant(_) => {
                        insert_ty(types, path, ast::DocType::EnumVariant);
                    }
                    ItemEnum::AssocConst { .. } => {
                        // Skip
                    }
                    ItemEnum::AssocType { .. } => {
                        // Skip
                    }
                    ItemEnum::ProcMacro(..) => {}
                    _ => todo!("{:?}", item),
                }
            }
        }
    }

    let mut types = HashSet::new();
    let krate = parse_doc(krate);

    recurse(
        &krate.index[&krate.root],
        krate,
        &mut types,
        Vec::new(),
        false,
        None,
    );

    types.into_iter()
}

fn run_util_api_enforcement() {
    let (component_crates, util_crates) = discover_workspace_crates();

    // Bucket 1: Definitely Stable util crates
    let bucket1_utils: HashSet<&str> = [
        "writeable",
        "fixed_decimal",
        "tinystr",
        "yoke",
        "yoke-derive",
        "zerofrom",
        "zerofrom-derive",
        "zerovec",
        "zerovec-derive",
    ]
    .into_iter()
    .collect();

    // Bucket 2: Ambiguous / Low-Risk util crates (restricted to explicit allowlist)
    let bucket2_allowlist: HashSet<(&str, &str)> = [
        ("icu_calendar", "calendrical_calculations"),
        ("icu_calendar", "ixdtf"),
        ("icu_time", "ixdtf"),
        ("icu_locale_core", "litemap"),
        ("icu_locale_core", "potential_utf"),
        ("icu_collections", "potential_utf"),
        ("icu_casemap", "potential_utf"),
        ("icu_datetime", "potential_utf"),
        ("icu_locale", "potential_utf"),
        ("icu_provider", "databake"),
        ("icu", "icu_pattern"),
        ("icu_datetime", "icu_pattern"),
        ("icu_decimal", "icu_pattern"),
        ("icu", "icu_experimental"),
    ]
    .into_iter()
    .collect();

    let bucket2_utils: HashSet<&str> = bucket2_allowlist.iter().map(|(_, u)| *u).collect();

    // Bucket 3: Default for all remaining util crates (Internal only)
    let bucket3_utils: HashSet<&str> = util_crates
        .iter()
        .map(|s| s.as_str())
        .filter(|u| !bucket1_utils.contains(u) && !bucket2_utils.contains(u))
        .collect();

    // Validate that bucket configuration stays in sync with workspace crates
    for u in &bucket1_utils {
        assert!(
            util_crates.contains(*u),
            "Bucket 1 util crate '{u}' does not exist in workspace!"
        );
    }
    for (c, u) in &bucket2_allowlist {
        assert!(
            component_crates.iter().any(|x| x == c),
            "Bucket 2 component crate '{c}' does not exist in workspace!"
        );
        assert!(
            util_crates.contains(*u),
            "Bucket 2 util crate '{u}' does not exist in workspace!"
        );
    }

    let mut all_violations = BTreeSet::new();
    for krate_name in &component_crates {
        let krate = parse_doc(krate_name);
        let mut checker = UtilApiChecker::new(
            krate_name,
            krate,
            &bucket2_allowlist,
            &bucket2_utils,
            &bucket3_utils,
        );
        checker.walk_item(&krate.root, false);
        all_violations.extend(checker.violations);
    }

    if !all_violations.is_empty() {
        eprintln!("\nUtil crate public API enforcement violations found:");
        for v in &all_violations {
            eprintln!("  [ERROR] {v}");
        }
        std::process::exit(1);
    }
}

fn discover_workspace_crates() -> (Vec<String>, HashSet<String>) {
    let metadata = cargo_metadata::MetadataCommand::new()
        .no_deps()
        .exec()
        .expect("failed to execute cargo metadata");

    let mut component_crates = Vec::new();
    let mut util_crates = HashSet::new();

    for pkg in metadata.packages {
        if pkg.name.ends_with("-dev") {
            continue;
        }

        let is_component = pkg
            .manifest_path
            .components()
            .any(|c| c.as_str() == "components")
            || (pkg
                .manifest_path
                .components()
                .any(|c| c.as_str() == "provider")
                && pkg.manifest_path.components().any(|c| c.as_str() == "core"));

        let is_utils_dir = pkg
            .manifest_path
            .components()
            .any(|c| c.as_str() == "utils");

        if is_component && pkg.version.major >= 1 {
            component_crates.push(pkg.name);
        } else if is_utils_dir || pkg.version.major == 0 {
            util_crates.insert(pkg.name);
        }
    }

    component_crates.sort();
    (component_crates, util_crates)
}

fn is_util_module_match(source: &str, util_name: &str) -> bool {
    let source_bytes = source.as_bytes();
    let util_len = util_name.len();

    if source_bytes.len() < util_len {
        return false;
    }

    let replaced = writeable::adapters::Replace {
        source: util_name,
        needle: "-",
        replacement: "_",
    };
    if writeable::cmp_utf8(&replaced, &source_bytes[..util_len]).is_ne() {
        return false;
    }

    if source_bytes.len() == util_len {
        return true;
    }

    source_bytes[util_len..].starts_with(b"::")
}

struct UtilApiChecker<'a, 'b> {
    krate_name: &'a str,
    krate: &'a Crate,
    bucket2_allowlist: &'b HashSet<(&'b str, &'b str)>,
    bucket2_utils: &'b HashSet<&'b str>,
    bucket3_utils: &'b HashSet<&'b str>,
    visited: HashSet<&'a Id>,
    referenced_buf: HashSet<&'a str>,
    violations: BTreeSet<String>,
}

impl<'a, 'b> UtilApiChecker<'a, 'b> {
    fn new(
        krate_name: &'a str,
        krate: &'a Crate,
        bucket2_allowlist: &'b HashSet<(&'b str, &'b str)>,
        bucket2_utils: &'b HashSet<&'b str>,
        bucket3_utils: &'b HashSet<&'b str>,
    ) -> Self {
        Self {
            krate_name,
            krate,
            bucket2_allowlist,
            bucket2_utils,
            bucket3_utils,
            visited: HashSet::new(),
            referenced_buf: HashSet::new(),
            violations: BTreeSet::new(),
        }
    }

    fn check_referenced_utils(&mut self, is_provider_item: bool, make_ctx: impl Fn() -> String) {
        let mut ctx: Option<String> = None;
        for &util in &self.referenced_buf {
            if self.bucket3_utils.contains(util) && !is_provider_item {
                let ctx_str = ctx.get_or_insert_with(&make_ctx);
                self.violations.insert(format!(
                    "Bucket 3 violation in {}::{ctx_str}: uses internal util '{util}'",
                    self.krate_name
                ));
            } else if self.bucket2_utils.contains(util)
                && !self.bucket2_allowlist.contains(&(self.krate_name, util))
            {
                let ctx_str = ctx.get_or_insert_with(&make_ctx);
                self.violations.insert(format!(
                    "Bucket 2 violation in {}::{ctx_str}: uses low-risk util '{util}' outside allowlist",
                    self.krate_name
                ));
            }
        }
    }

    fn walk_item(&mut self, id: &'a Id, is_provider: bool) {
        if !self.visited.insert(id) {
            return;
        }

        let Some(item) = self.krate.index.get(id) else {
            return;
        };

        if item.visibility != Visibility::Public {
            return;
        }

        let is_provider_item = is_provider
            || item.name.as_deref() == Some("provider")
            || item.name.as_deref() == Some("baked");

        match &item.inner {
            ItemEnum::Module(module) => {
                for child_id in &module.items {
                    self.walk_item(child_id, is_provider_item);
                }
            }
            ItemEnum::Use(import) => {
                if !is_provider_item {
                    for util in self.bucket3_utils {
                        if is_util_module_match(&import.source, util) {
                            self.violations.insert(format!(
                                "Bucket 3 violation in {}: pub use {}",
                                self.krate_name, import.source
                            ));
                        }
                    }
                }
                for util in self.bucket2_utils {
                    if is_util_module_match(&import.source, util)
                        && !self.bucket2_allowlist.contains(&(self.krate_name, util))
                    {
                        self.violations.insert(format!(
                            "Bucket 2 violation in {}: pub use {} (not allowlisted)",
                            self.krate_name, import.source
                        ));
                    }
                }
                if let Some(target_id) = &import.id {
                    self.walk_item(target_id, is_provider_item);
                }
            }
            ItemEnum::Function(func) => {
                self.referenced_buf.clear();
                for (_name, ty) in &func.sig.inputs {
                    get_type_crates(ty, self.krate, &mut self.referenced_buf);
                }
                if let Some(output) = &func.sig.output {
                    get_type_crates(output, self.krate, &mut self.referenced_buf);
                }
                self.check_referenced_utils(is_provider_item, || {
                    let item_name = item.name.as_deref().unwrap_or("<unnamed>");
                    format!("fn {item_name}")
                });
            }
            ItemEnum::Struct(struct_) => {
                let struct_name = item.name.as_deref().unwrap_or("<unnamed>");

                let fields_slice: &[Id] = match &struct_.kind {
                    StructKind::Plain { fields, .. } => fields,
                    StructKind::Tuple(fields) => {
                        for field_id in fields.iter().flatten() {
                            self.check_field(field_id, struct_name, is_provider_item);
                        }
                        &[]
                    }
                    _ => &[],
                };

                for field_id in fields_slice {
                    self.check_field(field_id, struct_name, is_provider_item);
                }

                for impl_id in &struct_.impls {
                    self.walk_impl(impl_id, is_provider_item);
                }
            }
            ItemEnum::Enum(enum_) => {
                let enum_name = item.name.as_deref().unwrap_or("<unnamed>");

                for variant_id in &enum_.variants {
                    if let Some(variant_item) = self.krate.index.get(variant_id)
                        && let ItemEnum::Variant(ref variant) = variant_item.inner
                    {
                        let variant_name = variant_item.name.as_deref().unwrap_or("<unnamed>");
                        match &variant.kind {
                            VariantKind::Plain => {}
                            VariantKind::Tuple(fields) => {
                                for field_id in fields.iter().flatten() {
                                    self.check_field(
                                        field_id,
                                        &format!("{enum_name}::{variant_name}"),
                                        is_provider_item,
                                    );
                                }
                            }
                            VariantKind::Struct { fields, .. } => {
                                for field_id in fields {
                                    self.check_field(
                                        field_id,
                                        &format!("{enum_name}::{variant_name}"),
                                        is_provider_item,
                                    );
                                }
                            }
                        }
                    }
                }

                for impl_id in &enum_.impls {
                    self.walk_impl(impl_id, is_provider_item);
                }
            }
            ItemEnum::TypeAlias(type_alias) => {
                self.referenced_buf.clear();
                get_type_crates(&type_alias.type_, self.krate, &mut self.referenced_buf);
                self.check_referenced_utils(is_provider_item, || {
                    let alias_name = item.name.as_deref().unwrap_or("<unnamed>");
                    format!("type {alias_name}")
                });
            }
            _ => {}
        }
    }

    fn check_field(&mut self, field_id: &'a Id, parent_ctx: &str, is_provider_item: bool) {
        if let Some(field_item) = self.krate.index.get(field_id)
            && field_item.visibility == Visibility::Public
            && let ItemEnum::StructField(ref fty) = field_item.inner
        {
            self.referenced_buf.clear();
            get_type_crates(fty, self.krate, &mut self.referenced_buf);
            self.check_referenced_utils(is_provider_item, || {
                let field_name = field_item.name.as_deref().unwrap_or("<unnamed>");
                format!("{parent_ctx}.{field_name}")
            });
        }
    }

    fn walk_impl(&mut self, impl_id: &'a Id, is_provider_item: bool) {
        if let Some(impl_item) = self.krate.index.get(impl_id)
            && let ItemEnum::Impl(ref impl_) = impl_item.inner
        {
            for method_id in &impl_.items {
                if let Some(method_item) = self.krate.index.get(method_id)
                    && method_item.visibility == Visibility::Public
                    && let ItemEnum::Function(ref func) = method_item.inner
                {
                    self.referenced_buf.clear();
                    for (_name, ty) in &func.sig.inputs {
                        get_type_crates(ty, self.krate, &mut self.referenced_buf);
                    }
                    if let Some(output) = &func.sig.output {
                        get_type_crates(output, self.krate, &mut self.referenced_buf);
                    }
                    self.check_referenced_utils(is_provider_item, || {
                        let fn_name = method_item.name.as_deref().unwrap_or("<unnamed>");
                        format!("fn {fn_name}")
                    });
                }
            }
        }
    }
}

fn get_type_crates<'a>(ty: &'a Type, krate: &'a Crate, crates: &mut HashSet<&'a str>) {
    match ty {
        Type::ResolvedPath(path) => {
            if let Some(item) = krate.paths.get(&path.id)
                && item.crate_id != 0
                && let Some(ext) = krate.external_crates.get(&item.crate_id)
            {
                crates.insert(ext.name.as_str());
            }
            if let Some(ref args) = path.args
                && let GenericArgs::AngleBracketed { ref args, .. } = **args
            {
                for arg in args {
                    if let GenericArg::Type(inner_ty) = arg {
                        get_type_crates(inner_ty, krate, crates);
                    }
                }
            }
        }
        Type::BorrowedRef { type_, .. }
        | Type::RawPointer { type_, .. }
        | Type::Slice(type_)
        | Type::Array { type_, .. } => {
            get_type_crates(type_, krate, crates);
        }
        Type::Tuple(types) => {
            for t in types {
                get_type_crates(t, krate, crates);
            }
        }
        Type::QualifiedPath {
            self_type, trait_, ..
        } => {
            get_type_crates(self_type, krate, crates);
            if let Some(t) = trait_
                && let Some(item) = krate.paths.get(&t.id)
                && item.crate_id != 0
                && let Some(ext) = krate.external_crates.get(&item.crate_id)
            {
                crates.insert(ext.name.as_str());
            }
        }
        _ => {}
    }
}
