# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "fused"
description = "High-precision fused floating-point algorithms"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
core_maths = { workspace = true }

[dev-dependencies]
num-bigint = { workspace = true }
num-rational = { workspace = true, features = ["std", "num-bigint"] }
num-traits = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }
