# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "fused"
version = "0.1.0"
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
default = []
std = []
serde = ["dep:serde", "serde/derive"]

[dependencies]
core_maths = { workspace = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
num-bigint = { workspace = true }
num-rational = { workspace = true }
num-traits = { workspace = true }
proptest = "1.0.0"
