# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu_codepointtrie_builder"
description = "Runtime builder for CodePointTrie"
version = "0.7.0"
categories.workspace = true
keywords = ["unicode", "collections", "internationalization"]
license = "Unicode-3.0"
include = [
    "src/**/*",
    "examples/**/*",
    "benches/**/*",
    "tests/**/*",
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "cpp/**/*"
]

authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.workspaces]
independent = true

[dependencies]
icu_collections = { workspace = true }
zerovec = { workspace = true, features = ["alloc"] }

[dev-dependencies]
icu = { path = "../../icu" }
wasmi = { workspace = true }
wat = { workspace = true }

[lints]
workspace = true
