pub(self) mod cldr_json {
    use crate::cldr_langid::CldrLangID;
    use icu_datetime::options::components::TimeZoneName;
    use serde::Deserialize;
    use std::borrow::Cow;

    pub struct Place {
        exemplar_city: Cow<'static, str>,
    }

    pub struct Argentina {
        pub rio_gallegos: Place,
        pub san_juan: Place,
        pub ushuaia: Place,
        pub la_rioja: Place,
        pub san_luis: Place,
        pub salta: Place,
        pub tucuman: Place,
    }

    pub struct Indiana {
        pub vincennes: Place,
        pub petersburg: Place,
        pub tell_city: Place,
        pub knox: Place,
        pub winamac: Place,
        pub marengo: Place,
        pub vevay: Place,
    }

    pub struct Kentucky {
        pub monticello: Place,
    }

    pub struct NorthDakota {
        pub beulah: Place,
        pub new_salem: Place,
        pub center: Place,
    }

    pub struct America {
        pub adak: Place,
        pub anchorage: Place,
        pub anguilla: Place,
        pub antigua: Place,
        pub araguaina: Place,
        pub argentina: Argentina,
        pub aruba: Place,
        pub asuncion: Place,
        pub bahia: Place,
        pub bahia_banderas: Place,
        pub barbados: Place,
        pub belem: Place,
        pub belize: Place,
        pub blanc_sablon: Place,
        pub boa_vista: Place,
        pub bogota: Place,
        pub boise: Place,
        pub buenos_aires: Place,
        pub cambridge_bay: Place,
        pub campo_grande: Place,
        pub cancun: Place,
        pub caracas: Place,
        pub catamarca: Place,
        pub cayenne: Place,
        pub cayman: Place,
        pub chicago: Place,
        pub chihuahua: Place,
        pub coral_harbour: Place,
        pub cordoba: Place,
        pub costa_rica: Place,
        pub creston: Place,
        pub cuiaba: Place,
        pub curacao: Place,
        pub danmarkshavn: Place,
        pub dawson: Place,
        pub dawson_creek: Place,
        pub denver: Place,
        pub detroit: Place,
        pub dominica: Place,
        pub edmonton: Place,
        pub eirunepe: Place,
        pub el_salvador: Place,
        pub fort_nelson: Place,
        pub fortaleza: Place,
        pub glace_bay: Place,
        pub godthab: Place,
        pub goose_bay: Place,
        pub grand_turk: Place,
        pub grenada: Place,
        pub guadeloupe: Place,
        pub guatemala: Place,
        pub guayaquil: Place,
        pub guyana: Place,
        pub halifax: Place,
        pub havana: Place,
        pub hermosillo: Place,
        pub indiana: Indiana,
        pub indianapolis: Place,
        pub inuvik: Place,
        pub iqaluit: Place,
        pub jamaica: Place,
        pub jujuy: Place,
        pub juneau: Place,
        pub kentucky: Kentucky,
        pub kralendijk: Place,
        pub la_paz: Place,
        pub lima: Place,
        pub los_angeles: Place,
        pub louisville: Place,
        pub lower_princes: Place,
        pub maceio: Place,
        pub managua: Place,
        pub manaus: Place,
        pub marigot: Place,
        pub martinique: Place,
        pub matamoros: Place,
        pub mazatlan: Place,
        pub mendoza: Place,
        pub menominee: Place,
        pub merida: Place,
        pub metlakatla: Place,
        pub mexico_city: Place,
        pub miquelon: Place,
        pub moncton: Place,
        pub monterrey: Place,
        pub montevideo: Place,
        pub montserrat: Place,
        pub nassau: Place,
        pub new_york: Place,
        pub nipigon: Place,
        pub nome: Place,
        pub noronha: Place,
        pub north_dakota: NorthDakota,
        pub ojinaga: Place,
        pub panama: Place,
        pub pangnirtung: Place,
        pub paramaribo: Place,
        pub phoenix: Place,
        pub port_au_prince: Place,
        pub port_of_spain: Place,
        pub porto_velho: Place,
        pub puerto_rico: Place,
        pub punta_arenas: Place,
        pub rainy_river: Place,
        pub rankin_inlet: Place,
        pub recife: Place,
        pub regina: Place,
        pub resolute: Place,
        pub rio_branco: Place,
        pub santarem: Place,
        pub santiago: Place,
        pub santo_domingo: Place,
        pub sao_paulo: Place,
        pub scoresbysund: Place,
        pub sitka: Place,
        pub st_barthelemy: Place,
        pub st_johns: Place,
        pub st_kitts: Place,
        pub st_lucia: Place,
        pub st_thomas: Place,
        pub st_vincent: Place,
        pub swift_current: Place,
        pub tegucigalpa: Place,
        pub thule: Place,
        pub thunder_bay: Place,
        pub tijuana: Place,
        pub toronto: Place,
        pub tortola: Place,
        pub vancouver: Place,
        pub whitehorse: Place,
        pub winnipeg: Place,
        pub yakutat: Place,
        pub yellowknife: Place,
    }
}
