// generated by diplomat-tool

part of 'lib.g.dart';

final class _CollatorOptionsFfi extends ffi.Struct {
  external _ResultInt32Void strength;
  external _ResultInt32Void alternateHandling;
  external _ResultInt32Void maxVariable;
  external _ResultInt32Void caseLevel;
  external _ResultInt32Void backwardSecondLevel;
}

/// See the [Rust documentation for `CollatorOptions`](https://docs.rs/icu/latest/icu/collator/struct.CollatorOptions.html) for more information.
final class CollatorOptions {
  CollatorStrength? strength;
  CollatorAlternateHandling? alternateHandling;
  CollatorMaxVariable? maxVariable;
  CollatorCaseLevel? caseLevel;
  CollatorBackwardSecondLevel? backwardSecondLevel;

  CollatorOptions({this.strength, this.alternateHandling, this.maxVariable, this.caseLevel, this.backwardSecondLevel});

  // This struct contains borrowed fields, so this takes in a list of
  // "edges" corresponding to where each lifetime's data may have been borrowed from
  // and passes it down to individual fields containing the borrow.
  // This method does not attempt to handle any dependencies between lifetimes, the caller
  // should handle this when constructing edge arrays.
  // ignore: unused_element
  CollatorOptions._fromFfi(_CollatorOptionsFfi ffi) :
    strength = ffi.strength.isOk ? CollatorStrength.values[ffi.strength.union.ok] : null,
    alternateHandling = ffi.alternateHandling.isOk ? CollatorAlternateHandling.values[ffi.alternateHandling.union.ok] : null,
    maxVariable = ffi.maxVariable.isOk ? CollatorMaxVariable.values[ffi.maxVariable.union.ok] : null,
    caseLevel = ffi.caseLevel.isOk ? CollatorCaseLevel.values[ffi.caseLevel.union.ok] : null,
    backwardSecondLevel = ffi.backwardSecondLevel.isOk ? CollatorBackwardSecondLevel.values[ffi.backwardSecondLevel.union.ok] : null;

  // ignore: unused_element
  _CollatorOptionsFfi _toFfi(ffi.Allocator temp) {
    final struct = ffi.Struct.create<_CollatorOptionsFfi>();
    CollatorStrength? strength = this.strength;
    struct.strength = strength != null ? _ResultInt32Void.ok(strength.index) : _ResultInt32Void.err();
    CollatorAlternateHandling? alternateHandling = this.alternateHandling;
    struct.alternateHandling = alternateHandling != null ? _ResultInt32Void.ok(alternateHandling.index) : _ResultInt32Void.err();
    CollatorMaxVariable? maxVariable = this.maxVariable;
    struct.maxVariable = maxVariable != null ? _ResultInt32Void.ok(maxVariable.index) : _ResultInt32Void.err();
    CollatorCaseLevel? caseLevel = this.caseLevel;
    struct.caseLevel = caseLevel != null ? _ResultInt32Void.ok(caseLevel.index) : _ResultInt32Void.err();
    CollatorBackwardSecondLevel? backwardSecondLevel = this.backwardSecondLevel;
    struct.backwardSecondLevel = backwardSecondLevel != null ? _ResultInt32Void.ok(backwardSecondLevel.index) : _ResultInt32Void.err();
    return struct;
  }

  @override
  bool operator ==(Object other) =>
      other is CollatorOptions &&
      other.strength == strength &&
      other.alternateHandling == alternateHandling &&
      other.maxVariable == maxVariable &&
      other.caseLevel == caseLevel &&
      other.backwardSecondLevel == backwardSecondLevel;

  @override
  int get hashCode => Object.hashAll([
        strength,
        alternateHandling,
        maxVariable,
        caseLevel,
        backwardSecondLevel,
      ]);
}
