// generated by diplomat-tool

part of 'lib.g.dart';

/// See the [Rust documentation for `CaseLevel`](https://docs.rs/icu/latest/icu/collator/enum.CaseLevel.html) for more information.
enum CollatorCaseLevel {
  off,

  on;
}
