// generated by diplomat-tool

part of 'lib.g.dart';

/// See the [Rust documentation for `CaseFirst`](https://docs.rs/icu/latest/icu/collator/enum.CaseFirst.html) for more information.
enum CollatorCaseFirst {
  off,

  lowerFirst,

  upperFirst;
}
