// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// 🚧 This API is experimental and may experience breaking changes outside major releases.
///
/// See the [Rust documentation for `Overflow`](https://docs.rs/icu/2.0.0/icu/calendar/options/enum.Overflow.html) for more information.
enum DateOverflow {

  constrain,

  reject;

}

// dart format on
