// generated by diplomat-tool

part of 'lib.g.dart';

/// Additional information: [1](https://docs.rs/fixed_decimal/latest/fixed_decimal/struct.LimitError.html)
enum FixedDecimalLimitError {
  todoZst;
}
