// generated by diplomat-tool

part of 'lib.g.dart';

/// Mode used in a rounding operation.
///
/// See the [Rust documentation for `RoundingMode`](https://docs.rs/fixed_decimal/latest/fixed_decimal/enum.RoundingMode.html) for more information.
enum FixedDecimalRoundingMode {
  ceil,

  expand,

  floor,

  trunc,

  halfCeil,

  halfExpand,

  halfFloor,

  halfTrunc,

  halfEven;
}
