// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// See the [Rust documentation for `IndicSyllabicCategory`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html) for more information.
enum IndicSyllabicCategory {
  /// See the [Rust documentation for `Other`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.Other) for more information.
  // ignore: public_member_api_docs
  other,
  /// See the [Rust documentation for `Avagraha`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.Avagraha) for more information.
  // ignore: public_member_api_docs
  avagraha,
  /// See the [Rust documentation for `Bindu`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.Bindu) for more information.
  // ignore: public_member_api_docs
  bindu,
  /// See the [Rust documentation for `BrahmiJoiningNumber`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.BrahmiJoiningNumber) for more information.
  // ignore: public_member_api_docs
  brahmiJoiningNumber,
  /// See the [Rust documentation for `CantillationMark`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.CantillationMark) for more information.
  // ignore: public_member_api_docs
  cantillationMark,
  /// See the [Rust documentation for `Consonant`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.Consonant) for more information.
  // ignore: public_member_api_docs
  consonant,
  /// See the [Rust documentation for `ConsonantDead`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.ConsonantDead) for more information.
  // ignore: public_member_api_docs
  consonantDead,
  /// See the [Rust documentation for `ConsonantFinal`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.ConsonantFinal) for more information.
  // ignore: public_member_api_docs
  consonantFinal,
  /// See the [Rust documentation for `ConsonantHeadLetter`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.ConsonantHeadLetter) for more information.
  // ignore: public_member_api_docs
  consonantHeadLetter,
  /// See the [Rust documentation for `ConsonantInitialPostfixed`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.ConsonantInitialPostfixed) for more information.
  // ignore: public_member_api_docs
  consonantInitialPostfixed,
  /// See the [Rust documentation for `ConsonantKiller`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.ConsonantKiller) for more information.
  // ignore: public_member_api_docs
  consonantKiller,
  /// See the [Rust documentation for `ConsonantMedial`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.ConsonantMedial) for more information.
  // ignore: public_member_api_docs
  consonantMedial,
  /// See the [Rust documentation for `ConsonantPlaceholder`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.ConsonantPlaceholder) for more information.
  // ignore: public_member_api_docs
  consonantPlaceholder,
  /// See the [Rust documentation for `ConsonantPrecedingRepha`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.ConsonantPrecedingRepha) for more information.
  // ignore: public_member_api_docs
  consonantPrecedingRepha,
  /// See the [Rust documentation for `ConsonantPrefixed`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.ConsonantPrefixed) for more information.
  // ignore: public_member_api_docs
  consonantPrefixed,
  /// See the [Rust documentation for `ConsonantSucceedingRepha`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.ConsonantSucceedingRepha) for more information.
  // ignore: public_member_api_docs
  consonantSucceedingRepha,
  /// See the [Rust documentation for `ConsonantSubjoined`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.ConsonantSubjoined) for more information.
  // ignore: public_member_api_docs
  consonantSubjoined,
  /// See the [Rust documentation for `ConsonantWithStacker`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.ConsonantWithStacker) for more information.
  // ignore: public_member_api_docs
  consonantWithStacker,
  /// See the [Rust documentation for `GeminationMark`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.GeminationMark) for more information.
  // ignore: public_member_api_docs
  geminationMark,
  /// See the [Rust documentation for `InvisibleStacker`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.InvisibleStacker) for more information.
  // ignore: public_member_api_docs
  invisibleStacker,
  /// See the [Rust documentation for `Joiner`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.Joiner) for more information.
  // ignore: public_member_api_docs
  joiner,
  /// See the [Rust documentation for `ModifyingLetter`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.ModifyingLetter) for more information.
  // ignore: public_member_api_docs
  modifyingLetter,
  /// See the [Rust documentation for `NonJoiner`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.NonJoiner) for more information.
  // ignore: public_member_api_docs
  nonJoiner,
  /// See the [Rust documentation for `Nukta`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.Nukta) for more information.
  // ignore: public_member_api_docs
  nukta,
  /// See the [Rust documentation for `Number`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.Number) for more information.
  // ignore: public_member_api_docs
  number,
  /// See the [Rust documentation for `NumberJoiner`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.NumberJoiner) for more information.
  // ignore: public_member_api_docs
  numberJoiner,
  /// See the [Rust documentation for `PureKiller`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.PureKiller) for more information.
  // ignore: public_member_api_docs
  pureKiller,
  /// See the [Rust documentation for `RegisterShifter`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.RegisterShifter) for more information.
  // ignore: public_member_api_docs
  registerShifter,
  /// See the [Rust documentation for `SyllableModifier`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.SyllableModifier) for more information.
  // ignore: public_member_api_docs
  syllableModifier,
  /// See the [Rust documentation for `ToneLetter`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.ToneLetter) for more information.
  // ignore: public_member_api_docs
  toneLetter,
  /// See the [Rust documentation for `ToneMark`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.ToneMark) for more information.
  // ignore: public_member_api_docs
  toneMark,
  /// See the [Rust documentation for `Virama`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.Virama) for more information.
  // ignore: public_member_api_docs
  virama,
  /// See the [Rust documentation for `Visarga`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.Visarga) for more information.
  // ignore: public_member_api_docs
  visarga,
  /// See the [Rust documentation for `Vowel`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.Vowel) for more information.
  // ignore: public_member_api_docs
  vowel,
  /// See the [Rust documentation for `VowelDependent`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.VowelDependent) for more information.
  // ignore: public_member_api_docs
  vowelDependent,
  /// See the [Rust documentation for `VowelIndependent`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.VowelIndependent) for more information.
  // ignore: public_member_api_docs
  vowelIndependent,
  /// See the [Rust documentation for `ReorderingKiller`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#associatedconstant.ReorderingKiller) for more information.
  // ignore: public_member_api_docs
  reorderingKiller;

  /// See the [Rust documentation for `for_char`](https://docs.rs/icu/2.1.1/icu/properties/props/trait.EnumeratedProperty.html#tymethod.for_char) for more information.
  static IndicSyllabicCategory forChar(Rune ch) {
    final result = _icu4x_IndicSyllabicCategory_for_char_mv1(ch);
    return IndicSyllabicCategory.values[result];
  }

  /// Convert to an integer value usable with ICU4C and CodePointMapData
  ///
  /// See the [Rust documentation for `to_icu4c_value`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#method.to_icu4c_value) for more information.
  int toIntegerValue() {
    final result = _icu4x_IndicSyllabicCategory_to_integer_value_mv1(index);
    return result;
  }

  /// Convert from an integer value from ICU4C or CodePointMapData
  ///
  /// See the [Rust documentation for `from_icu4c_value`](https://docs.rs/icu/2.1.1/icu/properties/props/struct.IndicSyllabicCategory.html#method.from_icu4c_value) for more information.
  static IndicSyllabicCategory? fromIntegerValue(int other) {
    final result = _icu4x_IndicSyllabicCategory_from_integer_value_mv1(other);
    if (!result.isOk) {
      return null;
    }
    return IndicSyllabicCategory.values[result.union.ok];
  }

}

@_DiplomatFfiUse('icu4x_IndicSyllabicCategory_for_char_mv1')
@ffi.Native<ffi.Int32 Function(ffi.Uint32)>(isLeaf: true, symbol: 'icu4x_IndicSyllabicCategory_for_char_mv1')
// ignore: non_constant_identifier_names
external int _icu4x_IndicSyllabicCategory_for_char_mv1(Rune ch);

@_DiplomatFfiUse('icu4x_IndicSyllabicCategory_to_integer_value_mv1')
@ffi.Native<ffi.Uint8 Function(ffi.Int32)>(isLeaf: true, symbol: 'icu4x_IndicSyllabicCategory_to_integer_value_mv1')
// ignore: non_constant_identifier_names
external int _icu4x_IndicSyllabicCategory_to_integer_value_mv1(int self);

@_DiplomatFfiUse('icu4x_IndicSyllabicCategory_from_integer_value_mv1')
@ffi.Native<_ResultInt32Void Function(ffi.Uint8)>(isLeaf: true, symbol: 'icu4x_IndicSyllabicCategory_from_integer_value_mv1')
// ignore: non_constant_identifier_names
external _ResultInt32Void _icu4x_IndicSyllabicCategory_from_integer_value_mv1(int other);

// dart format on
