// generated by diplomat-tool

part of 'lib.g.dart';

/// See the [Rust documentation for `TransformResult`](https://docs.rs/icu/latest/icu/locale/enum.TransformResult.html) for more information.
enum TransformResult {
  modified,

  unmodified;
}
