# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

[package]
name = "icu4x-datagen"
description = "Generate data for ICU4X DataProvider"
categories = ["internationalization", "localization", "development-tools"]
keywords = ["build-tool"]
license = "Unicode-3.0"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
icu_provider = { workspace = true }
icu = { workspace = true, features = ["datagen"] }
icu_provider_export = { workspace = true }
icu_provider_source = { workspace = true, optional = true }
icu_provider_registry = { workspace = true }

icu_provider_blob = { workspace = true, features = ["alloc"], optional = true }

clap = { workspace = true, features = ["derive"] }
displaydoc = { workspace = true }
eyre = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
simple_logger = { workspace = true }

[features]
default = ["networking", "fs_exporter", "blob_exporter", "baked_exporter", "provider", "rayon"]
provider = ["dep:icu_provider_source"]
baked_exporter = ["icu_provider_export/baked_exporter"]
blob_exporter = ["icu_provider_export/blob_exporter"]
blob_input = ["dep:icu_provider_blob", "icu/datagen"]
fs_exporter = ["icu_provider_export/fs_exporter"]
networking = ["icu_provider_source?/networking"]
unstable = ["icu_provider_source?/unstable", "icu/unstable"]
rayon = ["icu_provider_export/rayon"]

# Deprecated
use_wasm = []
use_icu4c = []

[package.metadata.cargo-all-features]
skip_optional_dependencies = true
# We have a *lot* of features here
max_combination_size = 3

[lints]
workspace = true
