// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";



/**
 * See the [Rust documentation for `Script`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html) for more information.
 */
export class Script {
    #value = undefined;

    static #values = new Map([
        ["Common", 0],
        ["Inherited", 1],
        ["Arabic", 2],
        ["Armenian", 3],
        ["Bengali", 4],
        ["Bopomofo", 5],
        ["Cherokee", 6],
        ["Coptic", 7],
        ["Cyrillic", 8],
        ["Deseret", 9],
        ["Devanagari", 10],
        ["Ethiopian", 11],
        ["Georgian", 12],
        ["Gothic", 13],
        ["Greek", 14],
        ["Gujarati", 15],
        ["Gurmukhi", 16],
        ["Han", 17],
        ["Hangul", 18],
        ["Hebrew", 19],
        ["Hiragana", 20],
        ["Kannada", 21],
        ["Katakana", 22],
        ["Khmer", 23],
        ["Lao", 24],
        ["Latin", 25],
        ["Malayalam", 26],
        ["Mongolian", 27],
        ["Myanmar", 28],
        ["Ogham", 29],
        ["OldItalic", 30],
        ["Oriya", 31],
        ["Runic", 32],
        ["Sinhala", 33],
        ["Syriac", 34],
        ["Tamil", 35],
        ["Telugu", 36],
        ["Thaana", 37],
        ["Thai", 38],
        ["Tibetan", 39],
        ["CanadianAboriginal", 40],
        ["Yi", 41],
        ["Tagalog", 42],
        ["Hanunoo", 43],
        ["Buhid", 44],
        ["Tagbanwa", 45],
        ["Braille", 46],
        ["Cypriot", 47],
        ["Limbu", 48],
        ["LinearB", 49],
        ["Osmanya", 50],
        ["Shavian", 51],
        ["TaiLe", 52],
        ["Ugaritic", 53],
        ["KatakanaOrHiragana", 54],
        ["Buginese", 55],
        ["Glagolitic", 56],
        ["Kharoshthi", 57],
        ["SylotiNagri", 58],
        ["NewTaiLue", 59],
        ["Tifinagh", 60],
        ["OldPersian", 61],
        ["Balinese", 62],
        ["Batak", 63],
        ["BlisSymbols", 64],
        ["Brahmi", 65],
        ["Cham", 66],
        ["Cirth", 67],
        ["OldChurchSlavonicCyrillic", 68],
        ["DemoticEgyptian", 69],
        ["HieraticEgyptian", 70],
        ["EgyptianHieroglyphs", 71],
        ["Khutsuri", 72],
        ["SimplifiedHan", 73],
        ["TraditionalHan", 74],
        ["PahawhHmong", 75],
        ["OldHungarian", 76],
        ["HarappanIndus", 77],
        ["Javanese", 78],
        ["KayahLi", 79],
        ["LatinFraktur", 80],
        ["LatinGaelic", 81],
        ["Lepcha", 82],
        ["LinearA", 83],
        ["Mandaic", 84],
        ["MayanHieroglyphs", 85],
        ["MeroiticHieroglyphs", 86],
        ["Nko", 87],
        ["OldTurkic", 88],
        ["OldPermic", 89],
        ["PhagsPa", 90],
        ["Phoenician", 91],
        ["Miao", 92],
        ["Rongorongo", 93],
        ["Sarati", 94],
        ["EstrangeloSyriac", 95],
        ["WesternSyriac", 96],
        ["EasternSyriac", 97],
        ["Tengwar", 98],
        ["Vai", 99],
        ["VisibleSpeech", 100],
        ["Cuneiform", 101],
        ["UnwrittenLanguages", 102],
        ["Unknown", 103],
        ["Carian", 104],
        ["Japanese", 105],
        ["TaiTham", 106],
        ["Lycian", 107],
        ["Lydian", 108],
        ["OlChiki", 109],
        ["Rejang", 110],
        ["Saurashtra", 111],
        ["SignWriting", 112],
        ["Sundanese", 113],
        ["Moon", 114],
        ["MeeteiMayek", 115],
        ["ImperialAramaic", 116],
        ["Avestan", 117],
        ["Chakma", 118],
        ["Korean", 119],
        ["Kaithi", 120],
        ["Manichaean", 121],
        ["InscriptionalPahlavi", 122],
        ["PsalterPahlavi", 123],
        ["BookPahlavi", 124],
        ["InscriptionalParthian", 125],
        ["Samaritan", 126],
        ["TaiViet", 127],
        ["MathematicalNotation", 128],
        ["Symbols", 129],
        ["Bamum", 130],
        ["Lisu", 131],
        ["NakhiGeba", 132],
        ["OldSouthArabian", 133],
        ["BassaVah", 134],
        ["Duployan", 135],
        ["Elbasan", 136],
        ["Grantha", 137],
        ["Kpelle", 138],
        ["Loma", 139],
        ["MendeKikakui", 140],
        ["MeroiticCursive", 141],
        ["OldNorthArabian", 142],
        ["Nabataean", 143],
        ["Palmyrene", 144],
        ["Khudawadi", 145],
        ["WarangCiti", 146],
        ["Afaka", 147],
        ["Jurchen", 148],
        ["Mro", 149],
        ["Nushu", 150],
        ["Sharada", 151],
        ["SoraSompeng", 152],
        ["Takri", 153],
        ["Tangut", 154],
        ["Woleai", 155],
        ["AnatolianHieroglyphs", 156],
        ["Khojki", 157],
        ["Tirhuta", 158],
        ["CaucasianAlbanian", 159],
        ["Mahajani", 160],
        ["Ahom", 161],
        ["Hatran", 162],
        ["Modi", 163],
        ["Multani", 164],
        ["PauCinHau", 165],
        ["Siddham", 166],
        ["Adlam", 167],
        ["Bhaiksuki", 168],
        ["Marchen", 169],
        ["Newa", 170],
        ["Osage", 171],
        ["HanWithBopomofo", 172],
        ["Jamo", 173],
        ["SymbolsEmoji", 174],
        ["MasaramGondi", 175],
        ["Soyombo", 176],
        ["ZanabazarSquare", 177],
        ["Dogra", 178],
        ["GunjalaGondi", 179],
        ["Makasar", 180],
        ["Medefaidrin", 181],
        ["HanifiRohingya", 182],
        ["Sogdian", 183],
        ["OldSogdian", 184],
        ["Elymaic", 185],
        ["NyiakengPuachueHmong", 186],
        ["Nandinagari", 187],
        ["Wancho", 188],
        ["Chorasmian", 189],
        ["DivesAkuru", 190],
        ["KhitanSmallScript", 191],
        ["Yezidi", 192],
        ["CyproMinoan", 193],
        ["OldUyghur", 194],
        ["Tangsa", 195],
        ["Toto", 196],
        ["Vithkuqi", 197],
        ["Kawi", 198],
        ["NagMundari", 199],
        ["Nastaliq", 200],
        ["Garay", 201],
        ["GurungKhema", 202],
        ["KiratRai", 203],
        ["OlOnal", 204],
        ["Sunuwar", 205],
        ["Todhri", 206],
        ["TuluTigalari", 207],
        ["BeriaErfe", 208],
        ["Sidetic", 209],
        ["TaiYo", 210],
        ["TolongSiki", 211],
        ["TraditionalHanWithLatin", 212],
        ["Chisoi", 254]
    ]);

    static getAllEntries() {
        return Script.#values.entries();
    }

    #internalConstructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return this;
            }
            return Script.#objectValues[arguments[1]];
        }

        if (value instanceof Script) {
            return value;
        }

        let intVal = Script.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal != null) {
            return Script.#objectValues[intVal];
        }

        throw TypeError(value + " is not a Script and does not correspond to any of its enumerator values.");
    }

    /** @internal */
    static fromValue(value) {
        return new Script(value);
    }

    get value(){
        for (let entry of Script.#values) {
            if (entry[1] == this.#value) {
                return entry[0];
            }
        }
    }

    /** @internal */
    get ffiValue(){
        return this.#value;
    }
    static #objectValues = {
        [0]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        [1]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
        [2]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 2),
        [3]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 3),
        [4]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 4),
        [5]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 5),
        [6]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 6),
        [7]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 7),
        [8]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 8),
        [9]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 9),
        [10]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 10),
        [11]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 11),
        [12]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 12),
        [13]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 13),
        [14]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 14),
        [15]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 15),
        [16]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 16),
        [17]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 17),
        [18]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 18),
        [19]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 19),
        [20]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 20),
        [21]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 21),
        [22]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 22),
        [23]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 23),
        [24]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 24),
        [25]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 25),
        [26]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 26),
        [27]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 27),
        [28]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 28),
        [29]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 29),
        [30]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 30),
        [31]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 31),
        [32]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 32),
        [33]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 33),
        [34]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 34),
        [35]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 35),
        [36]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 36),
        [37]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 37),
        [38]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 38),
        [39]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 39),
        [40]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 40),
        [41]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 41),
        [42]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 42),
        [43]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 43),
        [44]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 44),
        [45]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 45),
        [46]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 46),
        [47]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 47),
        [48]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 48),
        [49]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 49),
        [50]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 50),
        [51]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 51),
        [52]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 52),
        [53]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 53),
        [54]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 54),
        [55]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 55),
        [56]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 56),
        [57]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 57),
        [58]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 58),
        [59]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 59),
        [60]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 60),
        [61]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 61),
        [62]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 62),
        [63]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 63),
        [64]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 64),
        [65]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 65),
        [66]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 66),
        [67]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 67),
        [68]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 68),
        [69]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 69),
        [70]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 70),
        [71]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 71),
        [72]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 72),
        [73]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 73),
        [74]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 74),
        [75]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 75),
        [76]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 76),
        [77]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 77),
        [78]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 78),
        [79]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 79),
        [80]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 80),
        [81]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 81),
        [82]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 82),
        [83]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 83),
        [84]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 84),
        [85]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 85),
        [86]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 86),
        [87]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 87),
        [88]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 88),
        [89]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 89),
        [90]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 90),
        [91]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 91),
        [92]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 92),
        [93]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 93),
        [94]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 94),
        [95]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 95),
        [96]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 96),
        [97]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 97),
        [98]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 98),
        [99]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 99),
        [100]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 100),
        [101]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 101),
        [102]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 102),
        [103]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 103),
        [104]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 104),
        [105]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 105),
        [106]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 106),
        [107]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 107),
        [108]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 108),
        [109]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 109),
        [110]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 110),
        [111]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 111),
        [112]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 112),
        [113]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 113),
        [114]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 114),
        [115]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 115),
        [116]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 116),
        [117]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 117),
        [118]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 118),
        [119]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 119),
        [120]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 120),
        [121]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 121),
        [122]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 122),
        [123]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 123),
        [124]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 124),
        [125]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 125),
        [126]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 126),
        [127]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 127),
        [128]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 128),
        [129]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 129),
        [130]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 130),
        [131]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 131),
        [132]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 132),
        [133]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 133),
        [134]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 134),
        [135]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 135),
        [136]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 136),
        [137]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 137),
        [138]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 138),
        [139]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 139),
        [140]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 140),
        [141]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 141),
        [142]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 142),
        [143]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 143),
        [144]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 144),
        [145]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 145),
        [146]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 146),
        [147]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 147),
        [148]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 148),
        [149]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 149),
        [150]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 150),
        [151]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 151),
        [152]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 152),
        [153]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 153),
        [154]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 154),
        [155]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 155),
        [156]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 156),
        [157]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 157),
        [158]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 158),
        [159]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 159),
        [160]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 160),
        [161]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 161),
        [162]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 162),
        [163]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 163),
        [164]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 164),
        [165]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 165),
        [166]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 166),
        [167]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 167),
        [168]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 168),
        [169]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 169),
        [170]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 170),
        [171]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 171),
        [172]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 172),
        [173]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 173),
        [174]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 174),
        [175]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 175),
        [176]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 176),
        [177]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 177),
        [178]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 178),
        [179]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 179),
        [180]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 180),
        [181]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 181),
        [182]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 182),
        [183]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 183),
        [184]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 184),
        [185]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 185),
        [186]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 186),
        [187]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 187),
        [188]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 188),
        [189]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 189),
        [190]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 190),
        [191]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 191),
        [192]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 192),
        [193]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 193),
        [194]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 194),
        [195]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 195),
        [196]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 196),
        [197]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 197),
        [198]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 198),
        [199]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 199),
        [200]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 200),
        [201]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 201),
        [202]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 202),
        [203]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 203),
        [204]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 204),
        [205]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 205),
        [206]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 206),
        [207]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 207),
        [208]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 208),
        [209]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 209),
        [210]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 210),
        [211]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 211),
        [212]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 212),
        [254]: new Script(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 254),
    };

    /**
     * See the [Rust documentation for `Common`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Common) for more information.
     */
    static Common = Script.#objectValues[0];
    /**
     * See the [Rust documentation for `Inherited`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Inherited) for more information.
     */
    static Inherited = Script.#objectValues[1];
    /**
     * See the [Rust documentation for `Arabic`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Arabic) for more information.
     */
    static Arabic = Script.#objectValues[2];
    /**
     * See the [Rust documentation for `Armenian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Armenian) for more information.
     */
    static Armenian = Script.#objectValues[3];
    /**
     * See the [Rust documentation for `Bengali`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Bengali) for more information.
     */
    static Bengali = Script.#objectValues[4];
    /**
     * See the [Rust documentation for `Bopomofo`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Bopomofo) for more information.
     */
    static Bopomofo = Script.#objectValues[5];
    /**
     * See the [Rust documentation for `Cherokee`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Cherokee) for more information.
     */
    static Cherokee = Script.#objectValues[6];
    /**
     * See the [Rust documentation for `Coptic`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Coptic) for more information.
     */
    static Coptic = Script.#objectValues[7];
    /**
     * See the [Rust documentation for `Cyrillic`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Cyrillic) for more information.
     */
    static Cyrillic = Script.#objectValues[8];
    /**
     * See the [Rust documentation for `Deseret`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Deseret) for more information.
     */
    static Deseret = Script.#objectValues[9];
    /**
     * See the [Rust documentation for `Devanagari`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Devanagari) for more information.
     */
    static Devanagari = Script.#objectValues[10];
    /**
     * See the [Rust documentation for `Ethiopian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Ethiopian) for more information.
     */
    static Ethiopian = Script.#objectValues[11];
    /**
     * See the [Rust documentation for `Georgian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Georgian) for more information.
     */
    static Georgian = Script.#objectValues[12];
    /**
     * See the [Rust documentation for `Gothic`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Gothic) for more information.
     */
    static Gothic = Script.#objectValues[13];
    /**
     * See the [Rust documentation for `Greek`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Greek) for more information.
     */
    static Greek = Script.#objectValues[14];
    /**
     * See the [Rust documentation for `Gujarati`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Gujarati) for more information.
     */
    static Gujarati = Script.#objectValues[15];
    /**
     * See the [Rust documentation for `Gurmukhi`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Gurmukhi) for more information.
     */
    static Gurmukhi = Script.#objectValues[16];
    /**
     * See the [Rust documentation for `Han`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Han) for more information.
     */
    static Han = Script.#objectValues[17];
    /**
     * See the [Rust documentation for `Hangul`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Hangul) for more information.
     */
    static Hangul = Script.#objectValues[18];
    /**
     * See the [Rust documentation for `Hebrew`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Hebrew) for more information.
     */
    static Hebrew = Script.#objectValues[19];
    /**
     * See the [Rust documentation for `Hiragana`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Hiragana) for more information.
     */
    static Hiragana = Script.#objectValues[20];
    /**
     * See the [Rust documentation for `Kannada`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Kannada) for more information.
     */
    static Kannada = Script.#objectValues[21];
    /**
     * See the [Rust documentation for `Katakana`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Katakana) for more information.
     */
    static Katakana = Script.#objectValues[22];
    /**
     * See the [Rust documentation for `Khmer`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Khmer) for more information.
     */
    static Khmer = Script.#objectValues[23];
    /**
     * See the [Rust documentation for `Lao`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Lao) for more information.
     */
    static Lao = Script.#objectValues[24];
    /**
     * See the [Rust documentation for `Latin`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Latin) for more information.
     */
    static Latin = Script.#objectValues[25];
    /**
     * See the [Rust documentation for `Malayalam`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Malayalam) for more information.
     */
    static Malayalam = Script.#objectValues[26];
    /**
     * See the [Rust documentation for `Mongolian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Mongolian) for more information.
     */
    static Mongolian = Script.#objectValues[27];
    /**
     * See the [Rust documentation for `Myanmar`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Myanmar) for more information.
     */
    static Myanmar = Script.#objectValues[28];
    /**
     * See the [Rust documentation for `Ogham`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Ogham) for more information.
     */
    static Ogham = Script.#objectValues[29];
    /**
     * See the [Rust documentation for `OldItalic`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.OldItalic) for more information.
     */
    static OldItalic = Script.#objectValues[30];
    /**
     * See the [Rust documentation for `Oriya`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Oriya) for more information.
     */
    static Oriya = Script.#objectValues[31];
    /**
     * See the [Rust documentation for `Runic`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Runic) for more information.
     */
    static Runic = Script.#objectValues[32];
    /**
     * See the [Rust documentation for `Sinhala`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Sinhala) for more information.
     */
    static Sinhala = Script.#objectValues[33];
    /**
     * See the [Rust documentation for `Syriac`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Syriac) for more information.
     */
    static Syriac = Script.#objectValues[34];
    /**
     * See the [Rust documentation for `Tamil`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Tamil) for more information.
     */
    static Tamil = Script.#objectValues[35];
    /**
     * See the [Rust documentation for `Telugu`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Telugu) for more information.
     */
    static Telugu = Script.#objectValues[36];
    /**
     * See the [Rust documentation for `Thaana`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Thaana) for more information.
     */
    static Thaana = Script.#objectValues[37];
    /**
     * See the [Rust documentation for `Thai`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Thai) for more information.
     */
    static Thai = Script.#objectValues[38];
    /**
     * See the [Rust documentation for `Tibetan`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Tibetan) for more information.
     */
    static Tibetan = Script.#objectValues[39];
    /**
     * See the [Rust documentation for `CanadianAboriginal`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.CanadianAboriginal) for more information.
     */
    static CanadianAboriginal = Script.#objectValues[40];
    /**
     * See the [Rust documentation for `Yi`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Yi) for more information.
     */
    static Yi = Script.#objectValues[41];
    /**
     * See the [Rust documentation for `Tagalog`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Tagalog) for more information.
     */
    static Tagalog = Script.#objectValues[42];
    /**
     * See the [Rust documentation for `Hanunoo`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Hanunoo) for more information.
     */
    static Hanunoo = Script.#objectValues[43];
    /**
     * See the [Rust documentation for `Buhid`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Buhid) for more information.
     */
    static Buhid = Script.#objectValues[44];
    /**
     * See the [Rust documentation for `Tagbanwa`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Tagbanwa) for more information.
     */
    static Tagbanwa = Script.#objectValues[45];
    /**
     * See the [Rust documentation for `Braille`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Braille) for more information.
     */
    static Braille = Script.#objectValues[46];
    /**
     * See the [Rust documentation for `Cypriot`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Cypriot) for more information.
     */
    static Cypriot = Script.#objectValues[47];
    /**
     * See the [Rust documentation for `Limbu`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Limbu) for more information.
     */
    static Limbu = Script.#objectValues[48];
    /**
     * See the [Rust documentation for `LinearB`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.LinearB) for more information.
     */
    static LinearB = Script.#objectValues[49];
    /**
     * See the [Rust documentation for `Osmanya`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Osmanya) for more information.
     */
    static Osmanya = Script.#objectValues[50];
    /**
     * See the [Rust documentation for `Shavian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Shavian) for more information.
     */
    static Shavian = Script.#objectValues[51];
    /**
     * See the [Rust documentation for `TaiLe`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.TaiLe) for more information.
     */
    static TaiLe = Script.#objectValues[52];
    /**
     * See the [Rust documentation for `Ugaritic`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Ugaritic) for more information.
     */
    static Ugaritic = Script.#objectValues[53];
    /**
     * See the [Rust documentation for `KatakanaOrHiragana`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.KatakanaOrHiragana) for more information.
     */
    static KatakanaOrHiragana = Script.#objectValues[54];
    /**
     * See the [Rust documentation for `Buginese`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Buginese) for more information.
     */
    static Buginese = Script.#objectValues[55];
    /**
     * See the [Rust documentation for `Glagolitic`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Glagolitic) for more information.
     */
    static Glagolitic = Script.#objectValues[56];
    /**
     * See the [Rust documentation for `Kharoshthi`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Kharoshthi) for more information.
     */
    static Kharoshthi = Script.#objectValues[57];
    /**
     * See the [Rust documentation for `SylotiNagri`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.SylotiNagri) for more information.
     */
    static SylotiNagri = Script.#objectValues[58];
    /**
     * See the [Rust documentation for `NewTaiLue`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.NewTaiLue) for more information.
     */
    static NewTaiLue = Script.#objectValues[59];
    /**
     * See the [Rust documentation for `Tifinagh`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Tifinagh) for more information.
     */
    static Tifinagh = Script.#objectValues[60];
    /**
     * See the [Rust documentation for `OldPersian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.OldPersian) for more information.
     */
    static OldPersian = Script.#objectValues[61];
    /**
     * See the [Rust documentation for `Balinese`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Balinese) for more information.
     */
    static Balinese = Script.#objectValues[62];
    /**
     * See the [Rust documentation for `Batak`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Batak) for more information.
     */
    static Batak = Script.#objectValues[63];
    /**
     * See the [Rust documentation for `BlisSymbols`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.BlisSymbols) for more information.
     */
    static BlisSymbols = Script.#objectValues[64];
    /**
     * See the [Rust documentation for `Brahmi`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Brahmi) for more information.
     */
    static Brahmi = Script.#objectValues[65];
    /**
     * See the [Rust documentation for `Cham`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Cham) for more information.
     */
    static Cham = Script.#objectValues[66];
    /**
     * See the [Rust documentation for `Cirth`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Cirth) for more information.
     */
    static Cirth = Script.#objectValues[67];
    /**
     * See the [Rust documentation for `OldChurchSlavonicCyrillic`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.OldChurchSlavonicCyrillic) for more information.
     */
    static OldChurchSlavonicCyrillic = Script.#objectValues[68];
    /**
     * See the [Rust documentation for `DemoticEgyptian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.DemoticEgyptian) for more information.
     */
    static DemoticEgyptian = Script.#objectValues[69];
    /**
     * See the [Rust documentation for `HieraticEgyptian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.HieraticEgyptian) for more information.
     */
    static HieraticEgyptian = Script.#objectValues[70];
    /**
     * See the [Rust documentation for `EgyptianHieroglyphs`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.EgyptianHieroglyphs) for more information.
     */
    static EgyptianHieroglyphs = Script.#objectValues[71];
    /**
     * See the [Rust documentation for `Khutsuri`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Khutsuri) for more information.
     */
    static Khutsuri = Script.#objectValues[72];
    /**
     * See the [Rust documentation for `SimplifiedHan`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.SimplifiedHan) for more information.
     */
    static SimplifiedHan = Script.#objectValues[73];
    /**
     * See the [Rust documentation for `TraditionalHan`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.TraditionalHan) for more information.
     */
    static TraditionalHan = Script.#objectValues[74];
    /**
     * See the [Rust documentation for `PahawhHmong`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.PahawhHmong) for more information.
     */
    static PahawhHmong = Script.#objectValues[75];
    /**
     * See the [Rust documentation for `OldHungarian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.OldHungarian) for more information.
     */
    static OldHungarian = Script.#objectValues[76];
    /**
     * See the [Rust documentation for `HarappanIndus`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.HarappanIndus) for more information.
     */
    static HarappanIndus = Script.#objectValues[77];
    /**
     * See the [Rust documentation for `Javanese`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Javanese) for more information.
     */
    static Javanese = Script.#objectValues[78];
    /**
     * See the [Rust documentation for `KayahLi`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.KayahLi) for more information.
     */
    static KayahLi = Script.#objectValues[79];
    /**
     * See the [Rust documentation for `LatinFraktur`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.LatinFraktur) for more information.
     */
    static LatinFraktur = Script.#objectValues[80];
    /**
     * See the [Rust documentation for `LatinGaelic`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.LatinGaelic) for more information.
     */
    static LatinGaelic = Script.#objectValues[81];
    /**
     * See the [Rust documentation for `Lepcha`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Lepcha) for more information.
     */
    static Lepcha = Script.#objectValues[82];
    /**
     * See the [Rust documentation for `LinearA`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.LinearA) for more information.
     */
    static LinearA = Script.#objectValues[83];
    /**
     * See the [Rust documentation for `Mandaic`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Mandaic) for more information.
     */
    static Mandaic = Script.#objectValues[84];
    /**
     * See the [Rust documentation for `MayanHieroglyphs`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.MayanHieroglyphs) for more information.
     */
    static MayanHieroglyphs = Script.#objectValues[85];
    /**
     * See the [Rust documentation for `MeroiticHieroglyphs`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.MeroiticHieroglyphs) for more information.
     */
    static MeroiticHieroglyphs = Script.#objectValues[86];
    /**
     * See the [Rust documentation for `Nko`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Nko) for more information.
     */
    static Nko = Script.#objectValues[87];
    /**
     * See the [Rust documentation for `OldTurkic`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.OldTurkic) for more information.
     */
    static OldTurkic = Script.#objectValues[88];
    /**
     * See the [Rust documentation for `OldPermic`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.OldPermic) for more information.
     */
    static OldPermic = Script.#objectValues[89];
    /**
     * See the [Rust documentation for `PhagsPa`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.PhagsPa) for more information.
     */
    static PhagsPa = Script.#objectValues[90];
    /**
     * See the [Rust documentation for `Phoenician`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Phoenician) for more information.
     */
    static Phoenician = Script.#objectValues[91];
    /**
     * See the [Rust documentation for `Miao`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Miao) for more information.
     */
    static Miao = Script.#objectValues[92];
    /**
     * See the [Rust documentation for `Rongorongo`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Rongorongo) for more information.
     */
    static Rongorongo = Script.#objectValues[93];
    /**
     * See the [Rust documentation for `Sarati`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Sarati) for more information.
     */
    static Sarati = Script.#objectValues[94];
    /**
     * See the [Rust documentation for `EstrangeloSyriac`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.EstrangeloSyriac) for more information.
     */
    static EstrangeloSyriac = Script.#objectValues[95];
    /**
     * See the [Rust documentation for `WesternSyriac`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.WesternSyriac) for more information.
     */
    static WesternSyriac = Script.#objectValues[96];
    /**
     * See the [Rust documentation for `EasternSyriac`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.EasternSyriac) for more information.
     */
    static EasternSyriac = Script.#objectValues[97];
    /**
     * See the [Rust documentation for `Tengwar`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Tengwar) for more information.
     */
    static Tengwar = Script.#objectValues[98];
    /**
     * See the [Rust documentation for `Vai`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Vai) for more information.
     */
    static Vai = Script.#objectValues[99];
    /**
     * See the [Rust documentation for `VisibleSpeech`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.VisibleSpeech) for more information.
     */
    static VisibleSpeech = Script.#objectValues[100];
    /**
     * See the [Rust documentation for `Cuneiform`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Cuneiform) for more information.
     */
    static Cuneiform = Script.#objectValues[101];
    /**
     * See the [Rust documentation for `UnwrittenLanguages`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.UnwrittenLanguages) for more information.
     */
    static UnwrittenLanguages = Script.#objectValues[102];
    /**
     * See the [Rust documentation for `Unknown`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Unknown) for more information.
     */
    static Unknown = Script.#objectValues[103];
    /**
     * See the [Rust documentation for `Carian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Carian) for more information.
     */
    static Carian = Script.#objectValues[104];
    /**
     * See the [Rust documentation for `Japanese`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Japanese) for more information.
     */
    static Japanese = Script.#objectValues[105];
    /**
     * See the [Rust documentation for `TaiTham`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.TaiTham) for more information.
     */
    static TaiTham = Script.#objectValues[106];
    /**
     * See the [Rust documentation for `Lycian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Lycian) for more information.
     */
    static Lycian = Script.#objectValues[107];
    /**
     * See the [Rust documentation for `Lydian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Lydian) for more information.
     */
    static Lydian = Script.#objectValues[108];
    /**
     * See the [Rust documentation for `OlChiki`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.OlChiki) for more information.
     */
    static OlChiki = Script.#objectValues[109];
    /**
     * See the [Rust documentation for `Rejang`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Rejang) for more information.
     */
    static Rejang = Script.#objectValues[110];
    /**
     * See the [Rust documentation for `Saurashtra`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Saurashtra) for more information.
     */
    static Saurashtra = Script.#objectValues[111];
    /**
     * See the [Rust documentation for `SignWriting`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.SignWriting) for more information.
     */
    static SignWriting = Script.#objectValues[112];
    /**
     * See the [Rust documentation for `Sundanese`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Sundanese) for more information.
     */
    static Sundanese = Script.#objectValues[113];
    /**
     * See the [Rust documentation for `Moon`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Moon) for more information.
     */
    static Moon = Script.#objectValues[114];
    /**
     * See the [Rust documentation for `MeeteiMayek`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.MeeteiMayek) for more information.
     */
    static MeeteiMayek = Script.#objectValues[115];
    /**
     * See the [Rust documentation for `ImperialAramaic`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.ImperialAramaic) for more information.
     */
    static ImperialAramaic = Script.#objectValues[116];
    /**
     * See the [Rust documentation for `Avestan`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Avestan) for more information.
     */
    static Avestan = Script.#objectValues[117];
    /**
     * See the [Rust documentation for `Chakma`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Chakma) for more information.
     */
    static Chakma = Script.#objectValues[118];
    /**
     * See the [Rust documentation for `Korean`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Korean) for more information.
     */
    static Korean = Script.#objectValues[119];
    /**
     * See the [Rust documentation for `Kaithi`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Kaithi) for more information.
     */
    static Kaithi = Script.#objectValues[120];
    /**
     * See the [Rust documentation for `Manichaean`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Manichaean) for more information.
     */
    static Manichaean = Script.#objectValues[121];
    /**
     * See the [Rust documentation for `InscriptionalPahlavi`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.InscriptionalPahlavi) for more information.
     */
    static InscriptionalPahlavi = Script.#objectValues[122];
    /**
     * See the [Rust documentation for `PsalterPahlavi`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.PsalterPahlavi) for more information.
     */
    static PsalterPahlavi = Script.#objectValues[123];
    /**
     * See the [Rust documentation for `BookPahlavi`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.BookPahlavi) for more information.
     */
    static BookPahlavi = Script.#objectValues[124];
    /**
     * See the [Rust documentation for `InscriptionalParthian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.InscriptionalParthian) for more information.
     */
    static InscriptionalParthian = Script.#objectValues[125];
    /**
     * See the [Rust documentation for `Samaritan`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Samaritan) for more information.
     */
    static Samaritan = Script.#objectValues[126];
    /**
     * See the [Rust documentation for `TaiViet`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.TaiViet) for more information.
     */
    static TaiViet = Script.#objectValues[127];
    /**
     * See the [Rust documentation for `MathematicalNotation`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.MathematicalNotation) for more information.
     */
    static MathematicalNotation = Script.#objectValues[128];
    /**
     * See the [Rust documentation for `Symbols`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Symbols) for more information.
     */
    static Symbols = Script.#objectValues[129];
    /**
     * See the [Rust documentation for `Bamum`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Bamum) for more information.
     */
    static Bamum = Script.#objectValues[130];
    /**
     * See the [Rust documentation for `Lisu`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Lisu) for more information.
     */
    static Lisu = Script.#objectValues[131];
    /**
     * See the [Rust documentation for `NakhiGeba`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.NakhiGeba) for more information.
     */
    static NakhiGeba = Script.#objectValues[132];
    /**
     * See the [Rust documentation for `OldSouthArabian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.OldSouthArabian) for more information.
     */
    static OldSouthArabian = Script.#objectValues[133];
    /**
     * See the [Rust documentation for `BassaVah`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.BassaVah) for more information.
     */
    static BassaVah = Script.#objectValues[134];
    /**
     * See the [Rust documentation for `Duployan`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Duployan) for more information.
     */
    static Duployan = Script.#objectValues[135];
    /**
     * See the [Rust documentation for `Elbasan`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Elbasan) for more information.
     */
    static Elbasan = Script.#objectValues[136];
    /**
     * See the [Rust documentation for `Grantha`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Grantha) for more information.
     */
    static Grantha = Script.#objectValues[137];
    /**
     * See the [Rust documentation for `Kpelle`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Kpelle) for more information.
     */
    static Kpelle = Script.#objectValues[138];
    /**
     * See the [Rust documentation for `Loma`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Loma) for more information.
     */
    static Loma = Script.#objectValues[139];
    /**
     * See the [Rust documentation for `MendeKikakui`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.MendeKikakui) for more information.
     */
    static MendeKikakui = Script.#objectValues[140];
    /**
     * See the [Rust documentation for `MeroiticCursive`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.MeroiticCursive) for more information.
     */
    static MeroiticCursive = Script.#objectValues[141];
    /**
     * See the [Rust documentation for `OldNorthArabian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.OldNorthArabian) for more information.
     */
    static OldNorthArabian = Script.#objectValues[142];
    /**
     * See the [Rust documentation for `Nabataean`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Nabataean) for more information.
     */
    static Nabataean = Script.#objectValues[143];
    /**
     * See the [Rust documentation for `Palmyrene`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Palmyrene) for more information.
     */
    static Palmyrene = Script.#objectValues[144];
    /**
     * See the [Rust documentation for `Khudawadi`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Khudawadi) for more information.
     */
    static Khudawadi = Script.#objectValues[145];
    /**
     * See the [Rust documentation for `WarangCiti`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.WarangCiti) for more information.
     */
    static WarangCiti = Script.#objectValues[146];
    /**
     * See the [Rust documentation for `Afaka`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Afaka) for more information.
     */
    static Afaka = Script.#objectValues[147];
    /**
     * See the [Rust documentation for `Jurchen`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Jurchen) for more information.
     */
    static Jurchen = Script.#objectValues[148];
    /**
     * See the [Rust documentation for `Mro`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Mro) for more information.
     */
    static Mro = Script.#objectValues[149];
    /**
     * See the [Rust documentation for `Nushu`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Nushu) for more information.
     */
    static Nushu = Script.#objectValues[150];
    /**
     * See the [Rust documentation for `Sharada`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Sharada) for more information.
     */
    static Sharada = Script.#objectValues[151];
    /**
     * See the [Rust documentation for `SoraSompeng`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.SoraSompeng) for more information.
     */
    static SoraSompeng = Script.#objectValues[152];
    /**
     * See the [Rust documentation for `Takri`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Takri) for more information.
     */
    static Takri = Script.#objectValues[153];
    /**
     * See the [Rust documentation for `Tangut`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Tangut) for more information.
     */
    static Tangut = Script.#objectValues[154];
    /**
     * See the [Rust documentation for `Woleai`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Woleai) for more information.
     */
    static Woleai = Script.#objectValues[155];
    /**
     * See the [Rust documentation for `AnatolianHieroglyphs`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.AnatolianHieroglyphs) for more information.
     */
    static AnatolianHieroglyphs = Script.#objectValues[156];
    /**
     * See the [Rust documentation for `Khojki`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Khojki) for more information.
     */
    static Khojki = Script.#objectValues[157];
    /**
     * See the [Rust documentation for `Tirhuta`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Tirhuta) for more information.
     */
    static Tirhuta = Script.#objectValues[158];
    /**
     * See the [Rust documentation for `CaucasianAlbanian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.CaucasianAlbanian) for more information.
     */
    static CaucasianAlbanian = Script.#objectValues[159];
    /**
     * See the [Rust documentation for `Mahajani`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Mahajani) for more information.
     */
    static Mahajani = Script.#objectValues[160];
    /**
     * See the [Rust documentation for `Ahom`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Ahom) for more information.
     */
    static Ahom = Script.#objectValues[161];
    /**
     * See the [Rust documentation for `Hatran`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Hatran) for more information.
     */
    static Hatran = Script.#objectValues[162];
    /**
     * See the [Rust documentation for `Modi`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Modi) for more information.
     */
    static Modi = Script.#objectValues[163];
    /**
     * See the [Rust documentation for `Multani`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Multani) for more information.
     */
    static Multani = Script.#objectValues[164];
    /**
     * See the [Rust documentation for `PauCinHau`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.PauCinHau) for more information.
     */
    static PauCinHau = Script.#objectValues[165];
    /**
     * See the [Rust documentation for `Siddham`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Siddham) for more information.
     */
    static Siddham = Script.#objectValues[166];
    /**
     * See the [Rust documentation for `Adlam`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Adlam) for more information.
     */
    static Adlam = Script.#objectValues[167];
    /**
     * See the [Rust documentation for `Bhaiksuki`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Bhaiksuki) for more information.
     */
    static Bhaiksuki = Script.#objectValues[168];
    /**
     * See the [Rust documentation for `Marchen`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Marchen) for more information.
     */
    static Marchen = Script.#objectValues[169];
    /**
     * See the [Rust documentation for `Newa`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Newa) for more information.
     */
    static Newa = Script.#objectValues[170];
    /**
     * See the [Rust documentation for `Osage`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Osage) for more information.
     */
    static Osage = Script.#objectValues[171];
    /**
     * See the [Rust documentation for `HanWithBopomofo`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.HanWithBopomofo) for more information.
     */
    static HanWithBopomofo = Script.#objectValues[172];
    /**
     * See the [Rust documentation for `Jamo`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Jamo) for more information.
     */
    static Jamo = Script.#objectValues[173];
    /**
     * See the [Rust documentation for `SymbolsEmoji`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.SymbolsEmoji) for more information.
     */
    static SymbolsEmoji = Script.#objectValues[174];
    /**
     * See the [Rust documentation for `MasaramGondi`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.MasaramGondi) for more information.
     */
    static MasaramGondi = Script.#objectValues[175];
    /**
     * See the [Rust documentation for `Soyombo`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Soyombo) for more information.
     */
    static Soyombo = Script.#objectValues[176];
    /**
     * See the [Rust documentation for `ZanabazarSquare`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.ZanabazarSquare) for more information.
     */
    static ZanabazarSquare = Script.#objectValues[177];
    /**
     * See the [Rust documentation for `Dogra`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Dogra) for more information.
     */
    static Dogra = Script.#objectValues[178];
    /**
     * See the [Rust documentation for `GunjalaGondi`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.GunjalaGondi) for more information.
     */
    static GunjalaGondi = Script.#objectValues[179];
    /**
     * See the [Rust documentation for `Makasar`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Makasar) for more information.
     */
    static Makasar = Script.#objectValues[180];
    /**
     * See the [Rust documentation for `Medefaidrin`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Medefaidrin) for more information.
     */
    static Medefaidrin = Script.#objectValues[181];
    /**
     * See the [Rust documentation for `HanifiRohingya`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.HanifiRohingya) for more information.
     */
    static HanifiRohingya = Script.#objectValues[182];
    /**
     * See the [Rust documentation for `Sogdian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Sogdian) for more information.
     */
    static Sogdian = Script.#objectValues[183];
    /**
     * See the [Rust documentation for `OldSogdian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.OldSogdian) for more information.
     */
    static OldSogdian = Script.#objectValues[184];
    /**
     * See the [Rust documentation for `Elymaic`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Elymaic) for more information.
     */
    static Elymaic = Script.#objectValues[185];
    /**
     * See the [Rust documentation for `NyiakengPuachueHmong`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.NyiakengPuachueHmong) for more information.
     */
    static NyiakengPuachueHmong = Script.#objectValues[186];
    /**
     * See the [Rust documentation for `Nandinagari`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Nandinagari) for more information.
     */
    static Nandinagari = Script.#objectValues[187];
    /**
     * See the [Rust documentation for `Wancho`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Wancho) for more information.
     */
    static Wancho = Script.#objectValues[188];
    /**
     * See the [Rust documentation for `Chorasmian`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Chorasmian) for more information.
     */
    static Chorasmian = Script.#objectValues[189];
    /**
     * See the [Rust documentation for `DivesAkuru`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.DivesAkuru) for more information.
     */
    static DivesAkuru = Script.#objectValues[190];
    /**
     * See the [Rust documentation for `KhitanSmallScript`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.KhitanSmallScript) for more information.
     */
    static KhitanSmallScript = Script.#objectValues[191];
    /**
     * See the [Rust documentation for `Yezidi`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Yezidi) for more information.
     */
    static Yezidi = Script.#objectValues[192];
    /**
     * See the [Rust documentation for `CyproMinoan`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.CyproMinoan) for more information.
     */
    static CyproMinoan = Script.#objectValues[193];
    /**
     * See the [Rust documentation for `OldUyghur`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.OldUyghur) for more information.
     */
    static OldUyghur = Script.#objectValues[194];
    /**
     * See the [Rust documentation for `Tangsa`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Tangsa) for more information.
     */
    static Tangsa = Script.#objectValues[195];
    /**
     * See the [Rust documentation for `Toto`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Toto) for more information.
     */
    static Toto = Script.#objectValues[196];
    /**
     * See the [Rust documentation for `Vithkuqi`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Vithkuqi) for more information.
     */
    static Vithkuqi = Script.#objectValues[197];
    /**
     * See the [Rust documentation for `Kawi`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Kawi) for more information.
     */
    static Kawi = Script.#objectValues[198];
    /**
     * See the [Rust documentation for `NagMundari`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.NagMundari) for more information.
     */
    static NagMundari = Script.#objectValues[199];
    /**
     * See the [Rust documentation for `Nastaliq`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Nastaliq) for more information.
     */
    static Nastaliq = Script.#objectValues[200];
    /**
     * See the [Rust documentation for `Garay`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Garay) for more information.
     */
    static Garay = Script.#objectValues[201];
    /**
     * See the [Rust documentation for `GurungKhema`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.GurungKhema) for more information.
     */
    static GurungKhema = Script.#objectValues[202];
    /**
     * See the [Rust documentation for `KiratRai`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.KiratRai) for more information.
     */
    static KiratRai = Script.#objectValues[203];
    /**
     * See the [Rust documentation for `OlOnal`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.OlOnal) for more information.
     */
    static OlOnal = Script.#objectValues[204];
    /**
     * See the [Rust documentation for `Sunuwar`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Sunuwar) for more information.
     */
    static Sunuwar = Script.#objectValues[205];
    /**
     * See the [Rust documentation for `Todhri`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Todhri) for more information.
     */
    static Todhri = Script.#objectValues[206];
    /**
     * See the [Rust documentation for `TuluTigalari`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.TuluTigalari) for more information.
     */
    static TuluTigalari = Script.#objectValues[207];
    /**
     * See the [Rust documentation for `BeriaErfe`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.BeriaErfe) for more information.
     */
    static BeriaErfe = Script.#objectValues[208];
    /**
     * See the [Rust documentation for `Sidetic`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Sidetic) for more information.
     */
    static Sidetic = Script.#objectValues[209];
    /**
     * See the [Rust documentation for `TaiYo`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.TaiYo) for more information.
     */
    static TaiYo = Script.#objectValues[210];
    /**
     * See the [Rust documentation for `TolongSiki`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.TolongSiki) for more information.
     */
    static TolongSiki = Script.#objectValues[211];
    /**
     * See the [Rust documentation for `TraditionalHanWithLatin`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.TraditionalHanWithLatin) for more information.
     */
    static TraditionalHanWithLatin = Script.#objectValues[212];
    /**
     * See the [Rust documentation for `Chisoi`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#associatedconstant.Chisoi) for more information.
     */
    static Chisoi = Script.#objectValues[254];


    /**
     * See the [Rust documentation for `for_char`](https://docs.rs/icu/2.2.0/icu/properties/props/trait.EnumeratedProperty.html#tymethod.for_char) for more information.
     */
    static forChar(ch) {

        const result = wasm.icu4x_Script_for_char_mv1(ch);

        try {
            return new Script(diplomatRuntime.internalConstructor, result);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Get the "long" name of this property value (returns empty if property value is unknown)
     *
     * See the [Rust documentation for `get`](https://docs.rs/icu/2.2.0/icu/properties/struct.PropertyNamesLongBorrowed.html#method.get) for more information.
     */
    longName() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 9, 4, true);


        const result = wasm.icu4x_Script_long_name_mv1(diplomatReceive.buffer, this.ffiValue);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return new diplomatRuntime.DiplomatSliceStr(wasm, diplomatReceive.buffer,  "string8", []).getValue();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    /**
     * Get the "short" name of this property value (returns empty if property value is unknown)
     *
     * See the [Rust documentation for `get`](https://docs.rs/icu/2.2.0/icu/properties/struct.PropertyNamesShortBorrowed.html#method.get) for more information.
     */
    shortName() {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 9, 4, true);


        const result = wasm.icu4x_Script_short_name_mv1(diplomatReceive.buffer, this.ffiValue);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return new diplomatRuntime.DiplomatSliceStr(wasm, diplomatReceive.buffer,  "string8", []).getValue();
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    /**
     * Convert to an integer value usable with ICU4C and `CodePointMapData`
     *
     * See the [Rust documentation for `to_icu4c_value`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#method.to_icu4c_value) for more information.
     */
    toIntegerValue() {

        const result = wasm.icu4x_Script_to_integer_value_mv1(this.ffiValue);

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    /**
     * Convert from an integer value from ICU4C or `CodePointMapData`
     *
     * See the [Rust documentation for `from_icu4c_value`](https://docs.rs/icu/2.2.0/icu/properties/props/struct.Script.html#method.from_icu4c_value) for more information.
     */
    static fromIntegerValue(other) {
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.icu4x_Script_from_integer_value_mv1(diplomatReceive.buffer, other);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return new Script(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            diplomatReceive.free();
        }
    }

    static tryFromStr(s) {
        let functionCleanupArena = new diplomatRuntime.CleanupArena();

        const sSlice = functionCleanupArena.alloc(diplomatRuntime.DiplomatBuf.sliceWrapper(wasm, diplomatRuntime.DiplomatBuf.str8(wasm, s)));
        const diplomatReceive = new diplomatRuntime.DiplomatReceiveBuf(wasm, 5, 4, true);


        const result = wasm.icu4x_Script_try_from_str_mv1(diplomatReceive.buffer, sSlice.ptr);

        try {
            if (!diplomatReceive.resultFlag) {
                return null;
            }
            return new Script(diplomatRuntime.internalConstructor, diplomatRuntime.enumDiscriminant(wasm, diplomatReceive.buffer));
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
            functionCleanupArena.free();

            diplomatReceive.free();
        }
    }

    constructor(value) {
        return this.#internalConstructor(...arguments)
    }
}