#ifndef DateTimeFormatterGregorian_H
#define DateTimeFormatterGregorian_H

#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include "diplomat_runtime.h"

#include "DataProvider.d.h"
#include "DateTimeAlignment.d.h"
#include "DateTimeFormatterLoadError.d.h"
#include "DateTimeLength.d.h"
#include "IsoDate.d.h"
#include "Locale.d.h"
#include "NeoZonedDateTimeFormatterGregorian.d.h"
#include "Time.d.h"
#include "TimePrecision.d.h"
#include "YearStyle.d.h"

#include "DateTimeFormatterGregorian.d.h"






typedef struct icu4x_DateTimeFormatterGregorian_create_dt_mv1_result {union {DateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_create_dt_mv1_result;
icu4x_DateTimeFormatterGregorian_create_dt_mv1_result icu4x_DateTimeFormatterGregorian_create_dt_mv1(const Locale* locale, DateTimeLength_option length, TimePrecision_option time_precision, DateTimeAlignment_option alignment);

typedef struct icu4x_DateTimeFormatterGregorian_create_dt_with_provider_mv1_result {union {DateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_create_dt_with_provider_mv1_result;
icu4x_DateTimeFormatterGregorian_create_dt_with_provider_mv1_result icu4x_DateTimeFormatterGregorian_create_dt_with_provider_mv1(const DataProvider* provider, const Locale* locale, DateTimeLength_option length, TimePrecision_option time_precision, DateTimeAlignment_option alignment);

typedef struct icu4x_DateTimeFormatterGregorian_create_mdt_mv1_result {union {DateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_create_mdt_mv1_result;
icu4x_DateTimeFormatterGregorian_create_mdt_mv1_result icu4x_DateTimeFormatterGregorian_create_mdt_mv1(const Locale* locale, DateTimeLength_option length, TimePrecision_option time_precision, DateTimeAlignment_option alignment);

typedef struct icu4x_DateTimeFormatterGregorian_create_mdt_with_provider_mv1_result {union {DateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_create_mdt_with_provider_mv1_result;
icu4x_DateTimeFormatterGregorian_create_mdt_with_provider_mv1_result icu4x_DateTimeFormatterGregorian_create_mdt_with_provider_mv1(const DataProvider* provider, const Locale* locale, DateTimeLength_option length, TimePrecision_option time_precision, DateTimeAlignment_option alignment);

typedef struct icu4x_DateTimeFormatterGregorian_create_ymdt_mv1_result {union {DateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_create_ymdt_mv1_result;
icu4x_DateTimeFormatterGregorian_create_ymdt_mv1_result icu4x_DateTimeFormatterGregorian_create_ymdt_mv1(const Locale* locale, DateTimeLength_option length, TimePrecision_option time_precision, DateTimeAlignment_option alignment, YearStyle_option year_style);

typedef struct icu4x_DateTimeFormatterGregorian_create_ymdt_with_provider_mv1_result {union {DateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_create_ymdt_with_provider_mv1_result;
icu4x_DateTimeFormatterGregorian_create_ymdt_with_provider_mv1_result icu4x_DateTimeFormatterGregorian_create_ymdt_with_provider_mv1(const DataProvider* provider, const Locale* locale, DateTimeLength_option length, TimePrecision_option time_precision, DateTimeAlignment_option alignment, YearStyle_option year_style);

typedef struct icu4x_DateTimeFormatterGregorian_create_det_mv1_result {union {DateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_create_det_mv1_result;
icu4x_DateTimeFormatterGregorian_create_det_mv1_result icu4x_DateTimeFormatterGregorian_create_det_mv1(const Locale* locale, DateTimeLength_option length, TimePrecision_option time_precision, DateTimeAlignment_option alignment);

typedef struct icu4x_DateTimeFormatterGregorian_create_det_with_provider_mv1_result {union {DateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_create_det_with_provider_mv1_result;
icu4x_DateTimeFormatterGregorian_create_det_with_provider_mv1_result icu4x_DateTimeFormatterGregorian_create_det_with_provider_mv1(const DataProvider* provider, const Locale* locale, DateTimeLength_option length, TimePrecision_option time_precision, DateTimeAlignment_option alignment);

typedef struct icu4x_DateTimeFormatterGregorian_create_mdet_mv1_result {union {DateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_create_mdet_mv1_result;
icu4x_DateTimeFormatterGregorian_create_mdet_mv1_result icu4x_DateTimeFormatterGregorian_create_mdet_mv1(const Locale* locale, DateTimeLength_option length, TimePrecision_option time_precision, DateTimeAlignment_option alignment);

typedef struct icu4x_DateTimeFormatterGregorian_create_mdet_with_provider_mv1_result {union {DateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_create_mdet_with_provider_mv1_result;
icu4x_DateTimeFormatterGregorian_create_mdet_with_provider_mv1_result icu4x_DateTimeFormatterGregorian_create_mdet_with_provider_mv1(const DataProvider* provider, const Locale* locale, DateTimeLength_option length, TimePrecision_option time_precision, DateTimeAlignment_option alignment);

typedef struct icu4x_DateTimeFormatterGregorian_create_ymdet_mv1_result {union {DateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_create_ymdet_mv1_result;
icu4x_DateTimeFormatterGregorian_create_ymdet_mv1_result icu4x_DateTimeFormatterGregorian_create_ymdet_mv1(const Locale* locale, DateTimeLength_option length, TimePrecision_option time_precision, DateTimeAlignment_option alignment, YearStyle_option year_style);

typedef struct icu4x_DateTimeFormatterGregorian_create_ymdet_with_provider_mv1_result {union {DateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_create_ymdet_with_provider_mv1_result;
icu4x_DateTimeFormatterGregorian_create_ymdet_with_provider_mv1_result icu4x_DateTimeFormatterGregorian_create_ymdet_with_provider_mv1(const DataProvider* provider, const Locale* locale, DateTimeLength_option length, TimePrecision_option time_precision, DateTimeAlignment_option alignment, YearStyle_option year_style);

typedef struct icu4x_DateTimeFormatterGregorian_create_et_mv1_result {union {DateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_create_et_mv1_result;
icu4x_DateTimeFormatterGregorian_create_et_mv1_result icu4x_DateTimeFormatterGregorian_create_et_mv1(const Locale* locale, DateTimeLength_option length, TimePrecision_option time_precision, DateTimeAlignment_option alignment);

typedef struct icu4x_DateTimeFormatterGregorian_create_et_with_provider_mv1_result {union {DateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_create_et_with_provider_mv1_result;
icu4x_DateTimeFormatterGregorian_create_et_with_provider_mv1_result icu4x_DateTimeFormatterGregorian_create_et_with_provider_mv1(const DataProvider* provider, const Locale* locale, DateTimeLength_option length, TimePrecision_option time_precision, DateTimeAlignment_option alignment);

typedef struct icu4x_DateTimeFormatterGregorian_with_zone_generic_short_mv1_result {union {NeoZonedDateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_with_zone_generic_short_mv1_result;
icu4x_DateTimeFormatterGregorian_with_zone_generic_short_mv1_result icu4x_DateTimeFormatterGregorian_with_zone_generic_short_mv1(const DateTimeFormatterGregorian* self, const Locale* locale);

typedef struct icu4x_DateTimeFormatterGregorian_with_zone_generic_short_and_provider_mv1_result {union {NeoZonedDateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_with_zone_generic_short_and_provider_mv1_result;
icu4x_DateTimeFormatterGregorian_with_zone_generic_short_and_provider_mv1_result icu4x_DateTimeFormatterGregorian_with_zone_generic_short_and_provider_mv1(const DateTimeFormatterGregorian* self, const DataProvider* provider, const Locale* locale);

typedef struct icu4x_DateTimeFormatterGregorian_with_zone_generic_long_mv1_result {union {NeoZonedDateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_with_zone_generic_long_mv1_result;
icu4x_DateTimeFormatterGregorian_with_zone_generic_long_mv1_result icu4x_DateTimeFormatterGregorian_with_zone_generic_long_mv1(const DateTimeFormatterGregorian* self, const Locale* locale);

typedef struct icu4x_DateTimeFormatterGregorian_with_zone_generic_long_and_provider_mv1_result {union {NeoZonedDateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_with_zone_generic_long_and_provider_mv1_result;
icu4x_DateTimeFormatterGregorian_with_zone_generic_long_and_provider_mv1_result icu4x_DateTimeFormatterGregorian_with_zone_generic_long_and_provider_mv1(const DateTimeFormatterGregorian* self, const DataProvider* provider, const Locale* locale);

typedef struct icu4x_DateTimeFormatterGregorian_with_zone_specific_short_mv1_result {union {NeoZonedDateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_with_zone_specific_short_mv1_result;
icu4x_DateTimeFormatterGregorian_with_zone_specific_short_mv1_result icu4x_DateTimeFormatterGregorian_with_zone_specific_short_mv1(const DateTimeFormatterGregorian* self, const Locale* locale);

typedef struct icu4x_DateTimeFormatterGregorian_with_zone_specific_short_and_provider_mv1_result {union {NeoZonedDateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_with_zone_specific_short_and_provider_mv1_result;
icu4x_DateTimeFormatterGregorian_with_zone_specific_short_and_provider_mv1_result icu4x_DateTimeFormatterGregorian_with_zone_specific_short_and_provider_mv1(const DateTimeFormatterGregorian* self, const DataProvider* provider, const Locale* locale);

typedef struct icu4x_DateTimeFormatterGregorian_with_zone_specific_long_mv1_result {union {NeoZonedDateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_with_zone_specific_long_mv1_result;
icu4x_DateTimeFormatterGregorian_with_zone_specific_long_mv1_result icu4x_DateTimeFormatterGregorian_with_zone_specific_long_mv1(const DateTimeFormatterGregorian* self, const Locale* locale);

typedef struct icu4x_DateTimeFormatterGregorian_with_zone_specific_long_and_provider_mv1_result {union {NeoZonedDateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_with_zone_specific_long_and_provider_mv1_result;
icu4x_DateTimeFormatterGregorian_with_zone_specific_long_and_provider_mv1_result icu4x_DateTimeFormatterGregorian_with_zone_specific_long_and_provider_mv1(const DateTimeFormatterGregorian* self, const DataProvider* provider, const Locale* locale);

typedef struct icu4x_DateTimeFormatterGregorian_with_zone_localized_offset_short_mv1_result {union {NeoZonedDateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_with_zone_localized_offset_short_mv1_result;
icu4x_DateTimeFormatterGregorian_with_zone_localized_offset_short_mv1_result icu4x_DateTimeFormatterGregorian_with_zone_localized_offset_short_mv1(const DateTimeFormatterGregorian* self, const Locale* locale);

typedef struct icu4x_DateTimeFormatterGregorian_with_zone_localized_offset_short_and_provider_mv1_result {union {NeoZonedDateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_with_zone_localized_offset_short_and_provider_mv1_result;
icu4x_DateTimeFormatterGregorian_with_zone_localized_offset_short_and_provider_mv1_result icu4x_DateTimeFormatterGregorian_with_zone_localized_offset_short_and_provider_mv1(const DateTimeFormatterGregorian* self, const DataProvider* provider, const Locale* locale);

typedef struct icu4x_DateTimeFormatterGregorian_with_zone_localized_offset_long_mv1_result {union {NeoZonedDateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_with_zone_localized_offset_long_mv1_result;
icu4x_DateTimeFormatterGregorian_with_zone_localized_offset_long_mv1_result icu4x_DateTimeFormatterGregorian_with_zone_localized_offset_long_mv1(const DateTimeFormatterGregorian* self, const Locale* locale);

typedef struct icu4x_DateTimeFormatterGregorian_with_zone_localized_offset_long_and_provider_mv1_result {union {NeoZonedDateTimeFormatterGregorian* ok; DateTimeFormatterLoadError err;}; bool is_ok;} icu4x_DateTimeFormatterGregorian_with_zone_localized_offset_long_and_provider_mv1_result;
icu4x_DateTimeFormatterGregorian_with_zone_localized_offset_long_and_provider_mv1_result icu4x_DateTimeFormatterGregorian_with_zone_localized_offset_long_and_provider_mv1(const DateTimeFormatterGregorian* self, const DataProvider* provider, const Locale* locale);

void icu4x_DateTimeFormatterGregorian_format_iso_mv1(const DateTimeFormatterGregorian* self, const IsoDate* date, const Time* time, DiplomatWrite* write);


void icu4x_DateTimeFormatterGregorian_destroy_mv1(DateTimeFormatterGregorian* self);





#endif // DateTimeFormatterGregorian_H
