// generated by diplomat-tool
import type { CollatorOptionsV1 } from "./CollatorOptionsV1"
import type { CollatorResolvedOptionsV1 } from "./CollatorResolvedOptionsV1"
import type { DataProvider } from "./DataProvider"
import type { Locale } from "./Locale"
import type { pointer, char } from "./diplomat-runtime.d.ts";


/** See the [Rust documentation for `Collator`](https://docs.rs/icu/latest/icu/collator/struct.Collator.html) for more information.
*/
export class Collator {
    

    get ffiValue(): pointer;


    static createV1(provider: DataProvider, locale: Locale, options: CollatorOptionsV1): Collator;

    compareUtf16(left: string, right: string): number;

    compare(left: string, right: string): number;

    get resolvedOptions(): CollatorResolvedOptionsV1;

    

}