// generated by diplomat-tool
import type { CollationSortKey } from "./CollationSortKey"
import type { CollatorOptions } from "./CollatorOptions"
import type { CollatorOptions_obj } from "./CollatorOptions"
import type { CollatorResolvedOptions } from "./CollatorResolvedOptions"
import type { DataError } from "./DataError"
import type { DataProvider } from "./DataProvider"
import type { Locale } from "./Locale"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * See the [Rust documentation for `Collator`](https://docs.rs/icu/2.0.0/icu/collator/struct.Collator.html) for more information.
 */
export class Collator {
    /** @internal */
    get ffiValue(): pointer;


    /**
     * Construct a new Collator instance using a particular data source.
     *
     * See the [Rust documentation for `try_new`](https://docs.rs/icu/2.0.0/icu/collator/struct.Collator.html#method.try_new) for more information.
     */
    static createWithProvider(provider: DataProvider, locale: Locale, options: CollatorOptions_obj): Collator;

    /**
     * Compare two strings.
     *
     * Ill-formed input is treated as if errors had been replaced with REPLACEMENT CHARACTERs according
     * to the WHATWG Encoding Standard.
     *
     * See the [Rust documentation for `compare_utf16`](https://docs.rs/icu/2.0.0/icu/collator/struct.CollatorBorrowed.html#method.compare_utf16) for more information.
     */
    compare(left: string, right: string): number;

    /**
     * Compare two strings.
     *
     * Ill-formed input is treated as if errors had been replaced with REPLACEMENT CHARACTERs according
     * to the WHATWG Encoding Standard.
     *
     * See the [Rust documentation for `compare_latin1`](https://docs.rs/icu/2.0.0/icu/collator/struct.CollatorBorrowed.html#method.compare_latin1) for more information.
     */
    compareLatin1(left: Array<number>, right: Array<number>): number;

    /**
     * Compare two strings.
     *
     * Ill-formed input is treated as if errors had been replaced with REPLACEMENT CHARACTERs according
     * to the WHATWG Encoding Standard.
     *
     * See the [Rust documentation for `compare_latin1_utf16`](https://docs.rs/icu/2.0.0/icu/collator/struct.CollatorBorrowed.html#method.compare_latin1_utf16) for more information.
     */
    compareLatin1Utf16(left: Array<number>, right: string): number;

    /**
     * The resolved options showing how the default options, the requested options,
     * and the options from locale data were combined. None of the struct fields
     * will have `Auto` as the value.
     *
     * See the [Rust documentation for `resolved_options`](https://docs.rs/icu/2.0.0/icu/collator/struct.CollatorBorrowed.html#method.resolved_options) for more information.
     */
    get resolvedOptions(): CollatorResolvedOptions;

    /**
     * Produce the sort key for a given UTF-8 encoded string up to this collator's strength
     *
     * See the [Rust documentation for `write_sort_key_utf8_to`](https://docs.rs/icu/2.0.0/icu/collator/struct.CollatorBorrowed.html#method.write_sort_key_utf8_to) for more information.
     */
    sortKeyUtf8To(s: string): CollationSortKey;

    /**
     * Produce the sort key for a given UTF-16 encoded string up to this collator's strength
     *
     * See the [Rust documentation for `write_sort_key_utf16_to`](https://docs.rs/icu/2.0.0/icu/collator/struct.CollatorBorrowed.html#method.write_sort_key_utf16_to) for more information.
     */
    sortKeyUtf16To(s: string): CollationSortKey;

    /**
     * Construct a new Collator instance using compiled data.
     *
     * See the [Rust documentation for `try_new`](https://docs.rs/icu/2.0.0/icu/collator/struct.Collator.html#method.try_new) for more information.
     */
    constructor(locale: Locale, options: CollatorOptions_obj);
}