// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

// Base enumerator definition
/** See the [Rust documentation for `AlternateHandling`](https://docs.rs/icu/latest/icu/collator/enum.AlternateHandling.html) for more information.
*/
export class CollatorAlternateHandling {
    #value = undefined;

    static values = new Map([
        ["Auto", 0],
        ["NonIgnorable", 1],
        ["Shifted", 2]
    ]);

    constructor(value) {
        if (value instanceof CollatorAlternateHandling) {
            this.#value = value.value;
            return;
        }

        if (CollatorAlternateHandling.values.has(value)) {
            this.#value = value;
            return;
        }

        throw TypeError(value + " is not a CollatorAlternateHandling and does not correspond to any of its enumerator values.");
    }

    get value() {
        return this.#value;
    }

    get ffiValue() {
        return CollatorAlternateHandling.values.get(this.#value);
    }

    static Auto = new CollatorAlternateHandling("Auto");
    static NonIgnorable = new CollatorAlternateHandling("NonIgnorable");
    static Shifted = new CollatorAlternateHandling("Shifted");
}