// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";

type DecimalLimitError_obj = {
};



/**
 * Additional information: [1](https://docs.rs/fixed_decimal/0.7.0/fixed_decimal/struct.LimitError.html)
 */
export class DecimalLimitError {
    /** @internal */
    static fromFields(structObj : DecimalLimitError_obj) : DecimalLimitError;

    /**
    * Create `DecimalLimitError` from an object that contains all of `DecimalLimitError`s fields.
    * Optional fields do not need to be included in the provided object.
    */
    constructor(structObj: DecimalLimitError_obj);

}