import wasm from "./diplomat-wasm.mjs"
import * as diplomatRuntime from "./diplomat-runtime.mjs"

export const ICU4XError_js_to_rust = {
  "UnknownError": 0,
  "DataMissingDataMarkerError": 256,
  "DataMissingVariantError": 257,
  "DataMissingLocaleError": 258,
  "DataNeedsVariantError": 259,
  "DataNeedsLocaleError": 260,
  "DataExtraneousLocaleError": 261,
  "DataFilteredResourceError": 262,
  "DataMismatchedTypeError": 263,
  "DataMissingPayloadError": 264,
  "DataInvalidStateError": 265,
  "DataCustomError": 266,
  "DataIoError": 267,
  "DataUnavailableBufferFormatError": 268,
  "DataMismatchedAnyBufferError": 269,
  "PropertyUnexpectedPropertyNameError": 1026,
  "DateTimePatternError": 2048,
  "DateTimeMissingInputFieldError": 2049,
  "DateTimeSkeletonError": 2050,
  "DateTimeUnsupportedFieldError": 2051,
  "DateTimeUnsupportedOptionsError": 2052,
  "DateTimeMissingWeekdaySymbolError": 2053,
  "DateTimeMissingMonthSymbolError": 2054,
  "DateTimeFixedDecimalError": 2055,
  "DateTimeMismatchedCalendarError": 2056,
};

export const ICU4XError_rust_to_js = {
  [0]: "UnknownError",
  [256]: "DataMissingDataMarkerError",
  [257]: "DataMissingVariantError",
  [258]: "DataMissingLocaleError",
  [259]: "DataNeedsVariantError",
  [260]: "DataNeedsLocaleError",
  [261]: "DataExtraneousLocaleError",
  [262]: "DataFilteredResourceError",
  [263]: "DataMismatchedTypeError",
  [264]: "DataMissingPayloadError",
  [265]: "DataInvalidStateError",
  [266]: "DataCustomError",
  [267]: "DataIoError",
  [268]: "DataUnavailableBufferFormatError",
  [269]: "DataMismatchedAnyBufferError",
  [1026]: "PropertyUnexpectedPropertyNameError",
  [2048]: "DateTimePatternError",
  [2049]: "DateTimeMissingInputFieldError",
  [2050]: "DateTimeSkeletonError",
  [2051]: "DateTimeUnsupportedFieldError",
  [2052]: "DateTimeUnsupportedOptionsError",
  [2053]: "DateTimeMissingWeekdaySymbolError",
  [2054]: "DateTimeMissingMonthSymbolError",
  [2055]: "DateTimeFixedDecimalError",
  [2056]: "DateTimeMismatchedCalendarError",
};

export const ICU4XError = {
  "UnknownError": "UnknownError",
  "DataMissingDataMarkerError": "DataMissingDataMarkerError",
  "DataMissingVariantError": "DataMissingVariantError",
  "DataMissingLocaleError": "DataMissingLocaleError",
  "DataNeedsVariantError": "DataNeedsVariantError",
  "DataNeedsLocaleError": "DataNeedsLocaleError",
  "DataExtraneousLocaleError": "DataExtraneousLocaleError",
  "DataFilteredResourceError": "DataFilteredResourceError",
  "DataMismatchedTypeError": "DataMismatchedTypeError",
  "DataMissingPayloadError": "DataMissingPayloadError",
  "DataInvalidStateError": "DataInvalidStateError",
  "DataCustomError": "DataCustomError",
  "DataIoError": "DataIoError",
  "DataUnavailableBufferFormatError": "DataUnavailableBufferFormatError",
  "DataMismatchedAnyBufferError": "DataMismatchedAnyBufferError",
  "PropertyUnexpectedPropertyNameError": "PropertyUnexpectedPropertyNameError",
  "DateTimePatternError": "DateTimePatternError",
  "DateTimeMissingInputFieldError": "DateTimeMissingInputFieldError",
  "DateTimeSkeletonError": "DateTimeSkeletonError",
  "DateTimeUnsupportedFieldError": "DateTimeUnsupportedFieldError",
  "DateTimeUnsupportedOptionsError": "DateTimeUnsupportedOptionsError",
  "DateTimeMissingWeekdaySymbolError": "DateTimeMissingWeekdaySymbolError",
  "DateTimeMissingMonthSymbolError": "DateTimeMissingMonthSymbolError",
  "DateTimeFixedDecimalError": "DateTimeFixedDecimalError",
  "DateTimeMismatchedCalendarError": "DateTimeMismatchedCalendarError",
};
