// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

// Base enumerator definition
/** See the [Rust documentation for `IsoMinutes`](https://docs.rs/icu/latest/icu/datetime/time_zone/enum.IsoMinutes.html) for more information.
*/
export class IsoTimeZoneMinuteDisplay {
    #value = undefined;

    static #values = new Map([
        ["Required", 0],
        ["Optional", 1]
    ]);

    constructor(value) {
        if (arguments.length > 1 && arguments[0] === diplomatRuntime.internalConstructor) {
            // We pass in two internalConstructor arguments to create *new*
            // instances of this type, otherwise the enums are treated as singletons.
            if (arguments[1] === diplomatRuntime.internalConstructor ) {
                this.#value = arguments[2];
                return;
            }
            return IsoTimeZoneMinuteDisplay.#objectValues[arguments[1]];
        }

        if (value instanceof IsoTimeZoneMinuteDisplay) {
            return value;
        }

        let intVal = IsoTimeZoneMinuteDisplay.#values.get(value);

        // Nullish check, checks for null or undefined
        if (intVal == null) {
            return IsoTimeZoneMinuteDisplay.#objectValues[intVal];
        }

        throw TypeError(value + " is not a IsoTimeZoneMinuteDisplay and does not correspond to any of its enumerator values.");
    }

    get value() {
        return [...IsoTimeZoneMinuteDisplay.#values.keys()][this.#value];
    }

    get ffiValue() {
        return this.#value;
    }
    static #objectValues = [
        new IsoTimeZoneMinuteDisplay(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 0),
        new IsoTimeZoneMinuteDisplay(diplomatRuntime.internalConstructor, diplomatRuntime.internalConstructor, 1),
    ];

    static Required = IsoTimeZoneMinuteDisplay.#objectValues[0];
    static Optional = IsoTimeZoneMinuteDisplay.#objectValues[1];
}