// generated by diplomat-tool
import type { DataProvider } from "./DataProvider"
import type { SentenceBreakIteratorLatin1 } from "./SentenceBreakIteratorLatin1"
import type { SentenceBreakIteratorUtf16 } from "./SentenceBreakIteratorUtf16"
import type { SentenceBreakIteratorUtf8 } from "./SentenceBreakIteratorUtf8"
import type { pointer, char } from "./diplomat-runtime.d.ts";


/** An ICU4X sentence-break segmenter, capable of finding sentence breakpoints in strings.
*
*See the [Rust documentation for `SentenceSegmenter`](https://docs.rs/icu/latest/icu/segmenter/struct.SentenceSegmenter.html) for more information.
*/
export class SentenceSegmenter {
    

    get ffiValue(): pointer;


    static create(provider: DataProvider): SentenceSegmenter;

    segmentUtf8(input: string): SentenceBreakIteratorUtf8;

    segmentUtf16(input: string): SentenceBreakIteratorUtf16;

    segmentLatin1(input: Array<number>): SentenceBreakIteratorLatin1;

    

}