// generated by diplomat-tool
import type { DataProvider } from "./DataProvider"
import type { DateTimeFormatterLoadError } from "./DateTimeFormatterLoadError"
import type { DateTimeLength } from "./DateTimeLength"
import type { Locale } from "./Locale"
import type { Time } from "./Time"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";


/** An ICU4X TimeFormatter object capable of formatting an [`Time`] type (and others) as a string
*
*See the [Rust documentation for `TimeFormatter`](https://docs.rs/icu/latest/icu/datetime/type.TimeFormatter.html) for more information.
*
*Additional information: [1](https://docs.rs/icu/latest/icu/datetime/fieldsets/struct.T.html)
*/


export class TimeFormatter {
    
    get ffiValue(): pointer;

    static createWithLength(locale: Locale, length: DateTimeLength): TimeFormatter;

    static createWithLengthAndProvider(provider: DataProvider, locale: Locale, length: DateTimeLength): TimeFormatter;

    format(value: Time): string;
}